
let otherData = [{title:"Affairs of Anatol, The",date:"12/16/2021",portada:"Burning Bright"},
{title:"RocknRolla",date:"05/21/2022",portada:"Rollerball"},
{title:"Fortress",date:"10/03/2021",portada:"Man Facing Southeast (Hombre mirando al sudeste)"},
{title:"Raggedy Man",date:"06/09/2022",portada:"Best Man, The (Testimone dello sposo, Il)"},
{title:"Charms for the Easy Life",date:"01/27/2022",portada:"Shamus"},
{title:"Maria",date:"01/19/2022",portada:"Two Ninas"},
{title:"Not with My Wife, You Don't!",date:"11/05/2021",portada:"Ultramarines: A Warhammer 40,000 Movie"},
{title:"Days of Heaven",date:"03/02/2022",portada:"Appropriate Adult"},
{title:"Strangers, The",date:"07/31/2022",portada:"Maid of Salem"},
{title:"Chizuko's Younger Sister (Futari)",date:"10/13/2021",portada:"César"},
{title:"The Feminine Touch",date:"01/24/2022",portada:"House"},
{title:"Criminal Lovers",date:"05/20/2022",portada:"Auntie Mame"},
{title:"Parisienne, La (Une parisienne)",date:"05/19/2022",portada:"Brassed Off"},
{title:"Crazy as Hell",date:"04/28/2022",portada:"Death Wish 5: The Face of Death"},
{title:"All the President's Men",date:"08/22/2022",portada:"She Done Him Wrong"},
{title:"Pulling John",date:"02/24/2022",portada:"Garfield Gets Real"},
{title:"What Price Glory",date:"06/01/2022",portada:"Katalin Varga"},
{title:"Eichmann",date:"12/18/2021",portada:"Pollock"},
{title:"Hachiko: A Dog's Story (a.k.a. Hachi: A Dog's Tale)",date:"04/19/2022",portada:"Snow (Snijeg)"},
{title:"Friday the 13th Part VII: The New Blood",date:"03/11/2022",portada:"Crush, The"},
{title:"House of Games",date:"07/31/2022",portada:"Double Indemnity"},
{title:"Tropico",date:"04/17/2022",portada:"Franz Kafka's a Country Doctor"},
{title:"My Mom Is a Character (Minha Mãe é uma Peça: O Filme)",date:"07/12/2022",portada:"More the Merrier, The"},
{title:"They Won't Forget",date:"10/29/2021",portada:"Cheech & Chong's The Corsican Brothers"},
{title:"Alexandria... Why? (Iskanderija... lih?)",date:"09/30/2021",portada:"Film Unfinished, A (Shtikat Haarchion)"},
{title:"Ultrasuede: In Search of Halston",date:"06/09/2022",portada:"Synecdoche, New York"},
{title:"Afterschool",date:"07/10/2022",portada:"Rock 'N' Roll High School"},
{title:"Welcome to the Punch",date:"07/01/2022",portada:"Antiviral"},
{title:"The Batman vs. Dracula",date:"05/16/2022",portada:"From the Life of the Marionettes (Aus dem Leben der Marionetten) "},
{title:"Soldier's Plaything, A",date:"09/05/2022",portada:"Tripping the Rift: The Movie"},
{title:"Special When Lit",date:"12/27/2021",portada:"Mission: Impossible II"},
{title:"I Know Where I'm Going!",date:"10/15/2021",portada:"Dream Lover"},
{title:"Buried Alive II",date:"01/13/2022",portada:"Boyfriends and Girlfriends (a.k.a. My Girlfriend's Boyfriend) (L'ami de mon amie)"},
{title:"Passion of Ayn Rand, The",date:"03/10/2022",portada:"The Inhabited Island 2: Rebellion"},
{title:"Barbary Coast",date:"07/18/2022",portada:"Teacher, A"},
{title:"Hen, his wife",date:"02/16/2022",portada:"Escape from New York"},
{title:"Mei and the Kittenbus",date:"07/27/2022",portada:"Comic Book Confidential"},
{title:"Three Strangers",date:"06/01/2022",portada:"Counterfeit Traitor, The"},
{title:"Why Has Bodhi-Dharma Left for the East?: A Zen Fable (Dharmaga tongjoguro kan kkadalgun)",date:"06/24/2022",portada:"District 9"},
{title:"Men of Means",date:"03/06/2022",portada:"Backcountry"},
{title:"Friends and Family",date:"07/03/2022",portada:"Lost City, The"},
{title:"Song to Remember, A",date:"03/29/2022",portada:"I Want You"},
{title:"Stargate",date:"02/02/2022",portada:"Paramore Live, the Final Riot!"},
{title:"Rampage",date:"04/05/2022",portada:"Bordertown"},
{title:"Highball",date:"07/06/2022",portada:"Singing Detective, The"},
{title:"Dangerous Profession, A",date:"03/23/2022",portada:"Just an American Boy"},
{title:"Russian Ark (Russkiy Kovcheg)",date:"05/31/2022",portada:"Legend of Bigfoot, The"},
{title:"Land of Plenty (Angst and Alienation in America)",date:"11/19/2021",portada:"Freeze Frame"},
{title:"Fear Over the City",date:"04/25/2022",portada:"Lady in White (a.k.a. The Mystery of the Lady in White)"},
{title:"Reservation Road",date:"11/19/2021",portada:"Jails, Hospitals & Hip-Hop"},
{title:"Young Frankenstein",date:"10/21/2021",portada:"Mrs. Dalloway"},
{title:"27 Dresses",date:"01/16/2022",portada:"Semi-Pro"},
{title:"Wieners",date:"05/19/2022",portada:"Pokémon the Movie 2000"},
{title:"À l'aventure",date:"04/08/2022",portada:"Brothers Rico, The"},
{title:"American Beauty",date:"03/25/2022",portada:"The Prophecy: Forsaken"},
{title:"Get Over It",date:"01/11/2022",portada:"Four Nights of a Dreamer (Quatre nuits d'un rêveur)"},
{title:"Generale Della Rovere, Il",date:"04/17/2022",portada:"Pronto"},
{title:"Man of the Century",date:"07/19/2022",portada:"Kiss of the Vampire, The"},
{title:"Little Dieter Needs to Fly",date:"10/06/2021",portada:"Ray"},
{title:"Turbo: A Power Rangers Movie",date:"04/23/2022",portada:"Game of Chance (Onnenpeli)"},
{title:"Cheech & Chong's Nice Dreams",date:"09/20/2022",portada:"Singing Nun, The"},
{title:"Chesty: A Tribute to a Legend",date:"11/14/2021",portada:"Nymphomaniac: Volume I"},
{title:"Gospel of Judas, The",date:"05/20/2022",portada:"6th Man, The (Sixth Man, The)"},
{title:"Believers, The",date:"03/03/2022",portada:"Bionicle 3: Web of Shadows"},
{title:"Pretty One, The",date:"02/21/2022",portada:"Fool There Was, A"},
{title:"Topper Returns",date:"04/24/2022",portada:"Pauline & Paulette (Pauline en Paulette)"},
{title:"Country Girl, The",date:"10/24/2021",portada:"Caterina in the Big City (Caterina va in città)"},
{title:"Carbon Copy",date:"03/31/2022",portada:"Story of Xinghua, The (Xinghua san yue tian)"},
{title:"Mother of Mine (Äideistä parhain)",date:"11/09/2021",portada:"Dossier 51 (Dossier 51, Le)"},
{title:"Pianist, The",date:"10/26/2021",portada:"As Cool As I Am"},
{title:"Tokyo Sonata",date:"04/26/2022",portada:"Bon Cop, Bad Cop"},
{title:"Butterfly Girl",date:"06/20/2022",portada:"Conan the Barbarian"},
{title:"Legend of Lizzie Borden, The",date:"02/14/2022",portada:"Andy Hardy's Blonde Trouble"},
{title:"Beau Geste",date:"02/05/2022",portada:"Quiet Flows the Don (Tikhiy Don)"},
{title:"Godfather: Part II, The",date:"10/19/2021",portada:"Starlift"},
{title:"Face to Face (Ansikte mot ansikte)",date:"05/29/2022",portada:"Congress, The"},
{title:"Pickle, The",date:"08/03/2022",portada:"Clear History"},
{title:"Hickey and Boggs",date:"05/07/2022",portada:"Lower City (Cidade Baixa)"},
{title:"Look of Love, The",date:"01/15/2022",portada:"Kiss of the Dragon"},
{title:"Mon oncle d'Amérique",date:"11/14/2021",portada:"I Do: How to Get Married and Stay Single (Prête-moi ta main)"},
{title:"Bright Lights, Big City",date:"08/07/2022",portada:"Pretty in Pink"},
{title:"Across the Bridge",date:"08/29/2022",portada:"Blindsight"},
{title:"Tobruk",date:"05/16/2022",portada:"Alive"},
{title:"Ballad of a Soldier (Ballada o soldate)",date:"01/02/2022",portada:"Captive (Cautiva) "},
{title:"The Reunion",date:"10/27/2021",portada:"Dust of Time, The"},
{title:"Bluebeard",date:"10/19/2021",portada:"MatchMaker, The"},
{title:"Day After Tomorrow, The",date:"03/13/2022",portada:"Milky Way, The"},
{title:"Strange Wilderness",date:"07/10/2022",portada:"Miracles"},
{title:"Class of 1999 II: The Substitute",date:"06/13/2022",portada:"Konga"},
{title:"Target",date:"06/14/2022",portada:"Rebellion (L'ordre et la morale)"},
{title:"Omega Doom",date:"08/16/2022",portada:"Hava Nagila: The Movie"},
{title:"Palo Alto",date:"08/24/2022",portada:"Full of It"},
{title:"Never a Dull Moment",date:"12/26/2021",portada:"Marie Antoinette"},
{title:"I Love You, Beth Cooper",date:"05/28/2022",portada:"Gold Rush, The"},
{title:"For the Love of Movies",date:"06/14/2022",portada:"Capture of Bigfoot, The"},
{title:"Poker Club, The",date:"02/10/2022",portada:"Crucible, The"},
{title:"Liliom",date:"07/10/2022",portada:"Corridor, The (Koridorius)"},
{title:"High and Dizzy",date:"01/16/2022",portada:"Everybody Street"},
{title:"Tour De Force (Hin und weg)",date:"05/22/2022",portada:"Big Sky, The"},
{title:"Clear History",date:"04/20/2022",portada:"Jungle Book"},
{title:"Brooklyn Castle",date:"04/07/2022",portada:"T-Rex: Back to the Cretaceous"},
{title:"Yes Or No",date:"11/03/2021",portada:"Flight of the Intruder"},
{title:"Godzilla vs. The Sea Monster (Gojira-Ebira-Mosura: Nankai no daiketto)",date:"11/11/2021",portada:"Hammer, The"},
{title:"Elsa & Fred",date:"09/15/2022",portada:"It's Pat"},
{title:"Secret of NIMH 2: Timmy to the Rescue, The",date:"09/14/2022",portada:"Children Underground"},
{title:"Boost, The",date:"07/16/2022",portada:"Chain of Command"},
{title:"Alice (Neco z Alenky)",date:"12/14/2021",portada:"Velocity of Gary, The"},
{title:"Donovan's Echo",date:"05/15/2022",portada:"Ladybugs"},
{title:"Gamera vs. Viras ",date:"01/02/2022",portada:"Rabbit Hole"},
{title:"Hidden, The",date:"06/26/2022",portada:"Dallas"},
{title:"Conspiracy, The",date:"03/29/2022",portada:"Rendez-vous"},
{title:"Dakota Skye",date:"08/10/2022",portada:"The Count of Monte Cristo"},
{title:"Outsider",date:"09/04/2022",portada:"Callan"},
{title:"Belle of the Nineties",date:"07/02/2022",portada:"Secret Society"},
{title:"Rahtree: Flower of the Night (Buppha Rahtree)",date:"11/10/2021",portada:"Botany of Desire, The"},
{title:"Matilda",date:"06/12/2022",portada:"This Is Elvis"},
{title:"Where Were You When the Lights Went Out?",date:"04/20/2022",portada:"Comedy of Terrors, The"},
{title:"Billy Liar",date:"08/23/2022",portada:"Wrestling Ernest Hemingway"},
{title:"Five Star Final",date:"12/20/2021",portada:"På sista versen"},
{title:"Manson",date:"07/15/2022",portada:"Jesus liebt mich"},
{title:"Between Strangers",date:"03/08/2022",portada:"Seducing Doctor Lewis (Grande séduction, La)"},
{title:"Survive Style 5+",date:"10/30/2021",portada:"Rush: Beyond the Lighted Stage"},
{title:"Rabbit",date:"07/05/2022",portada:"Rory O'Shea Was Here (Inside I'm Dancing)"},
{title:"Hucksters, The",date:"03/28/2022",portada:"Pandora's Box"},
{title:"World War II: When Lions Roared",date:"06/23/2022",portada:"Bus 174 (Ônibus 174)"},
{title:"City, The (Ciudad, La)",date:"11/04/2021",portada:"Los Flamencos"},
{title:"I'll See You in My Dreams",date:"12/27/2021",portada:"Testament of Orpheus, The (Testament d'Orphée)"},
{title:"Bag Man, The",date:"08/23/2022",portada:"Club Paradise"},
{title:"Safe",date:"10/27/2021",portada:"Next"},
{title:"Rosario Tijeras",date:"12/10/2021",portada:"Bullet for the General, A (Quién Sabe?)"},
{title:"Son of Flubber",date:"06/23/2022",portada:"Murder of Fred Hampton, The"},
{title:"Something New",date:"08/14/2022",portada:"Carry on Cabby"},
{title:"Civil Action, A",date:"01/15/2022",portada:"Casque d'or"},
{title:"Every Stewardess Goes to Heaven (Todas las azafatas van al cielo)",date:"05/22/2022",portada:"White Fang 2: Myth of the White Wolf"},
{title:"Claire's Knee (Genou de Claire, Le)",date:"09/30/2021",portada:"Bartok the Magnificent"},
{title:"Code Unknown (Code inconnu: Récit incomplet de divers voyages)",date:"10/06/2021",portada:"Perifery (Härmä)"},
{title:"Everything I Can See From Here",date:"03/29/2022",portada:"Mystery Date"},
{title:"The Strange Affair",date:"06/26/2022",portada:"Snow Falling on Cedars"},
{title:"Duelist (Hyeongsa)",date:"11/13/2021",portada:"Lucrèce Borgia"},
{title:"Land and Freedom (Tierra y libertad)",date:"01/22/2022",portada:"Ninja Scroll (Jûbei ninpûchô)"},
{title:"Front Page, The",date:"04/08/2022",portada:"Man Exposed"},
{title:"Gamera vs. Barugon",date:"01/22/2022",portada:"3 Backyards"},
{title:"Emotion",date:"11/19/2021",portada:"Violence at Noon (Hakuchu no torima)"},
{title:"Homeboy",date:"06/17/2022",portada:"Please Vote for Me"},
{title:"Jungle Fighters",date:"10/19/2021",portada:"Shampoo"},
{title:"Fantomas vs. Scotland Yard",date:"08/24/2022",portada:"Kumiko, the Treasure Hunter"},
{title:"Il Capitano",date:"01/28/2022",portada:"Hotel Terminus: The Life and Times of Klaus Barbie (Hôtel Terminus)"},
{title:"21",date:"08/26/2022",portada:"Battle of Algiers, The (La battaglia di Algeri)"},
{title:"Jo Jo Dancer, Your Life is Calling",date:"09/19/2022",portada:"House of Games"},
{title:"Sleepless Night (Nuit blanche)",date:"11/23/2021",portada:"Midnight Cowboy"},
{title:"Fandango",date:"02/24/2022",portada:"Dinner for Schmucks"},
{title:"Sliver",date:"07/18/2022",portada:"Parallel Sons"},
{title:"Summer School",date:"07/12/2022",portada:"Fay Grim"},
{title:"Divine Trash",date:"01/16/2022",portada:"Terror Within, The"},
{title:"Camelot",date:"01/08/2022",portada:"Saw VI"},
{title:"A.K.",date:"12/25/2021",portada:"Pulp Fiction"},
{title:"Broadway Danny Rose",date:"03/11/2022",portada:"Jasminum"},
{title:"My Mother Likes Women (A mi madre le gustan las mujeres)",date:"12/15/2021",portada:"Dark Crystal, The"},
{title:"Without Love",date:"12/15/2021",portada:"Rebel, The (Le Rebelle)"},
{title:"Read It and Weep",date:"11/16/2021",portada:"Family Jewels, The"},
{title:"96 Minutes ",date:"02/24/2022",portada:"Stay Hungry"},
{title:"So Much Water",date:"09/27/2022",portada:"Fear"},
{title:"Maybe, Maybe Not (Bewegte Mann, Der)",date:"12/23/2021",portada:"Crusades, The"},
{title:"The Last Wagon",date:"10/30/2021",portada:"Bar Girls"},
{title:"Shrek the Third",date:"09/16/2022",portada:"Pocahontas II: Journey to a New World "},
{title:"My Name Is Joe",date:"04/26/2022",portada:"Penny Serenade"},
{title:"Stone",date:"10/08/2021",portada:"X: The Unknown"},
{title:"In Search of the Castaways",date:"10/29/2021",portada:"Promise, The (La promesse)"},
{title:"Ghost Rider",date:"02/04/2022",portada:"Jump Tomorrow"},
{title:"Rampage",date:"10/23/2021",portada:"Vow, The"},
{title:"Queen - Rock Montreal",date:"04/29/2022",portada:"Patriot, The"},
{title:"American Me",date:"12/14/2021",portada:"Even the Rain (También la lluvia)"},
{title:"Cracks",date:"01/08/2022",portada:"Hollow Triumph (a.k.a. The Scar)"},
{title:"Torrid Zone",date:"12/07/2021",portada:"Blind Mountain (Mang shan)"},
{title:"Hiding Out",date:"01/18/2022",portada:"Relax... It's Just Sex"},
{title:"Story of Me, The (O contador de histórias)",date:"05/17/2022",portada:"Mister 880"},
{title:"World's Greatest Athlete, The",date:"05/17/2022",portada:"Saratoga"},
{title:"Zombie Girl: The Movie",date:"07/05/2022",portada:"Vääpeli Körmy ja kahtesti laukeava"},
{title:"Bey Yaar",date:"11/07/2021",portada:"Once Bitten"},
{title:"Adventures of Rocky and Bullwinkle, The",date:"07/12/2022",portada:"Born to Dance"},
{title:"S.O.B.",date:"03/14/2022",portada:"Anna: 6-18 (Anna: Ot shesti do vosemnadtsati)"},
{title:"Pallbearer, The",date:"03/18/2022",portada:"Life with Mikey"},
{title:"Sparrows Dance",date:"01/14/2022",portada:"Krrish 3"},
{title:"Kite Runner, The",date:"04/08/2022",portada:"Curious Case of Benjamin Button, The"},
{title:"Objective, Burma!",date:"05/13/2022",portada:"Going Places (Valseuses, Les)"},
{title:"Best Man, The",date:"07/26/2022",portada:"Heaven's Gate"},
{title:"Carmina or Blow Up (Carmina o revienta)",date:"01/02/2022",portada:"Details, The"},
{title:"Symphonie pastorale, La",date:"11/18/2021",portada:"Saga of Gosta Berling, The (Gösta Berlings saga)"},
{title:"In the Name of the King III",date:"05/14/2022",portada:"Where the Rivers Flow North"},
{title:"Mackintosh Man, The",date:"09/27/2022",portada:"Ed's Next Move"},
{title:"Last Airbender, The",date:"11/16/2021",portada:"Hiding Out"},
{title:"Big Time Operators (Smallest Show on Earth, The)",date:"11/09/2021",portada:"Esther Kahn"},
{title:"Criminal Justice",date:"03/17/2022",portada:"Rendition"},
{title:"À nous la liberté (Freedom for Us)",date:"10/08/2021",portada:"Debt, The"},
{title:"My Soul to Take",date:"07/17/2022",portada:"Park Row"},
{title:"Silver Bullet (Stephen King's Silver Bullet)",date:"01/30/2022",portada:"Clear History"},
{title:"Cigarettes and Coffee (Un cartus de kent si un pachet de cafea)",date:"12/28/2021",portada:"Electric Shadows (Meng ying tong nian)"},
{title:"Erased (Expatriate, The)",date:"10/24/2021",portada:"My Name is Juani (Yo soy la Juani)"},
{title:"Dangerous Corner",date:"05/19/2022",portada:"Mighty Joe Young"},
{title:"Roads to Koktebel (Koktebel)",date:"03/29/2022",portada:"Evilspeak"},
{title:"Silver Linings Playbook",date:"04/04/2022",portada:"Sleep Room, The"},
{title:"Rhapsody in Blue",date:"04/26/2022",portada:"Melbourne"},
{title:"Double, Double, Toil and Trouble",date:"12/07/2021",portada:"Sunday"},
{title:"Marine Story, A",date:"02/27/2022",portada:"What Price Glory"},
{title:"Raiders of the Lost Ark: The Adaptation",date:"02/22/2022",portada:"12 Angry Men"},
{title:"Trance",date:"01/05/2022",portada:"Last Will of Dr. Mabuse, The (Testament du Dr. Mabuse, Le)"},
{title:"Now You See Him, Now You Don't",date:"12/13/2021",portada:"Koi... Mil Gaya"},
{title:"Mission London",date:"03/18/2022",portada:"Wonderland"},
{title:"22 Bullets (L'immortel)",date:"07/29/2022",portada:"Repentance (Monanieba)"},
{title:"End of the Spear",date:"03/24/2022",portada:"Bloodstone: Subspecies II"},
{title:"Kill! (Kiru)",date:"06/03/2022",portada:"Winter of Discontent"},
{title:"Thomas Pynchon: A Journey into the Mind of P.",date:"12/14/2021",portada:"War of the Wildcats (In Old Oklahoma)"},
{title:"Luna de Avellaneda",date:"12/24/2021",portada:"Lon Chaney: A Thousand Faces"},
{title:"Anything for Her (Pour elle)",date:"07/24/2022",portada:"Rusalochka (The Little Mermaid)"},
{title:"Love's Long Journey",date:"09/06/2022",portada:"Roman de gare"},
{title:"Radiohead: Meeting People Is Easy",date:"12/22/2021",portada:"Mister Johnson"},
{title:"Ed Wood",date:"11/11/2021",portada:"August"},
{title:"A Gathering of Eagles",date:"04/22/2022",portada:"Tokyo!"},
{title:"Story Written with Water, A (Mizu de kakareta monogatari)",date:"12/01/2021",portada:"Sessions, The (Surrogate, The)"},
{title:"The Stanford Prison Experiment",date:"03/12/2022",portada:"Union Station"},
{title:"Poppy Shakespeare",date:"02/05/2022",portada:"Blob, The"},
{title:"Class of 92, The",date:"12/03/2021",portada:"Travelling Players, The (O thiasos)"},
{title:"Marked for Death",date:"07/23/2022",portada:"Hulk Vs."},
{title:"Joy Ride 2: Dead Ahead",date:"07/16/2022",portada:"The Big Bus"},
{title:"Antwone Fisher",date:"07/14/2022",portada:"Midsummer Night's Dream, A"},
{title:"As it is in Heaven (Så som i himmelen)",date:"08/10/2022",portada:"Cathedral, The (Katedra)"},
{title:"Raiders From Beneath the Sea",date:"09/09/2022",portada:"My Avatar and Me (Min Avatar og mig)"},
{title:"Lips of Blood (Lèvres de sang)",date:"01/30/2022",portada:"Wedding Song, The "},
{title:"If Lucy Fell",date:"08/04/2022",portada:"Legend of Hell House, The"},
{title:"Blood and Chocolate",date:"11/30/2021",portada:"Freedom"},
{title:"Expect No Mercy",date:"04/18/2022",portada:"I Am Ali"},
{title:"Amore (L'Amore)",date:"02/12/2022",portada:"Black Camel, The (Charlie Chan in the Black Camel)"},
{title:"Wallace & Gromit: A Close Shave",date:"01/08/2022",portada:"Night Watch (Nochnoy dozor)"},
{title:"Annie",date:"01/23/2022",portada:"Year My Parents Went on Vacation, The (O Ano em Que Meus Pais Saíram de Férias)"},
{title:"Year Ago in Winter, A (Im Winter ein Jahr)",date:"12/11/2021",portada:"Uncle Buck"},
{title:"Mondo Trasho",date:"07/11/2022",portada:"Testament of Orpheus, The (Testament d'Orphée)"},
{title:"Lost World: Jurassic Park, The",date:"04/13/2022",portada:"Baby Doll"},
{title:"Short Cuts",date:"07/16/2022",portada:"Race the Sun"},
{title:"This Christmas",date:"01/12/2022",portada:"Then I Sentenced Them All to Death (Atunci i-am condamnat pe toti la moarte)"},
{title:"Wooden Bridge, The",date:"09/02/2022",portada:"No. 1 Ladies' Detective Agency, The"},
{title:"Housekeeper, The (femme de ménage, Une)",date:"10/10/2021",portada:"Before the Fall (NaPolA - Elite für den Führer)"},
{title:"Brighton Rock",date:"11/27/2021",portada:"Batman: Mystery of the Batwoman"},
{title:"Apollo 13: To the Edge and Back",date:"02/14/2022",portada:"Magnificent Seven Ride!, The"},
{title:"Superdad",date:"12/13/2021",portada:"Mount St. Elias"},
{title:"Bad Girls",date:"10/02/2021",portada:"Mulan"},
{title:"The Happy Road",date:"08/15/2022",portada:"Wedding Song, The "},
{title:"Prince & Me, The",date:"05/05/2022",portada:"Guilty (Présumé coupable)"},
{title:"Behind the Burly Q: The Story of Burlesque in America",date:"10/24/2021",portada:"Black Hole, The"},
{title:"Whoregasm",date:"06/05/2022",portada:"Gothic"},
{title:"Cheech & Chong's Nice Dreams",date:"03/23/2022",portada:"Dear Jesse"},
{title:"Finding Joy",date:"05/07/2022",portada:"No Good Deed (a.k.a. The House on Turk Street)"},
{title:"Don 2",date:"01/29/2022",portada:"Art of War III: Retribution, The"},
{title:"Country Girl, The",date:"12/13/2021",portada:"The Inspector"},
{title:"Governess, The",date:"10/21/2021",portada:"M for Mother (Mim mesle madar)"},
{title:"Samurai Assassin (Samurai)",date:"05/12/2022",portada:"Devil's Playground"},
{title:"Small Town Girl",date:"11/16/2021",portada:"I Accuse"},
{title:"Ghost and Mrs. Muir, The",date:"10/19/2021",portada:"My Favorite Blonde"},
{title:"Get Low",date:"05/24/2022",portada:"Buster Keaton: A Hard Act to Follow"},
{title:"Daar",date:"04/26/2022",portada:"Wedding Party, The (Die Bluthochzeit)"},
{title:"Two Times Lotte",date:"05/03/2022",portada:"Ocean Heaven "},
{title:"Andy Hardy Meets Debutante",date:"11/28/2021",portada:"Red: Werewolf Hunter"},
{title:"Spark: A Burning Man Story",date:"12/02/2021",portada:"With Love... from the Age of Reason"},
{title:"Lupin the Third: The Secret of Mamo",date:"06/14/2022",portada:"Siege, The"},
{title:"Boundin'",date:"02/23/2022",portada:"Premium Rush"},
{title:"Poolhall Junkies",date:"06/05/2022",portada:"Danika"},
{title:"Max Payne",date:"02/07/2022",portada:"Silent Night, Deadly Night Part 2"},
{title:"Paradise Lost: The Child Murders at Robin Hood Hills",date:"09/23/2022",portada:"Salsa"},
{title:"Head in the Clouds",date:"07/03/2022",portada:"Heist"},
{title:"Adult World",date:"05/15/2022",portada:"Man with One Red Shoe, The"},
{title:"Dreamboat",date:"12/29/2021",portada:"Sharkwater"},
{title:"Beastly",date:"12/23/2021",portada:"Stevie Nicks: Live at Red Rocks"},
{title:"Beyond the Gates of Splendor",date:"12/02/2021",portada:"Stay Cool"},
{title:"Gremlins",date:"06/15/2022",portada:"Wild Card"},
{title:"Stone Reader",date:"09/11/2022",portada:"Year One, The (L'an 01)"},
{title:"Oslo, August 31st (Oslo, 31. august)",date:"11/22/2021",portada:"Road to Zanzibar"},
{title:"Mistress of Spices, The",date:"12/06/2021",portada:"Autumn Leaves"},
{title:"Retro Puppet Master (Puppet Master 7)",date:"04/11/2022",portada:"Element of Crime, The (Forbrydelsens Element)"},
{title:"Confessions of an Opium Eater",date:"09/28/2022",portada:"Computer Chess"},
{title:"Charge of the Light Brigade, The",date:"10/22/2021",portada:"Relationship Status: It's Complicated"},
{title:"A Kind of America 2",date:"05/02/2022",portada:"Two Brothers (Deux frères)"},
{title:"The Whisperer in Darkness",date:"11/18/2021",portada:"Tremors 3: Back to Perfection"},
{title:"Holiday Affair",date:"05/14/2022",portada:"Enid"},
{title:"Jimmy Show, The",date:"03/30/2022",portada:"Jodorowsky's Dune"},
{title:"Wrong Turn 4",date:"03/23/2022",portada:"Haunted Echoes"},
{title:"Van, The",date:"08/15/2022",portada:"Groundstar Conspiracy, The"},
{title:"Father and Son (Otets i syn)",date:"04/16/2022",portada:"Far from Home"},
{title:"Monsterman (Monsterimies)",date:"04/25/2022",portada:"Kit Kittredge: An American Girl"},
{title:"Little Dorrit",date:"01/22/2022",portada:"Disgrace"},
{title:"Pharaoh's Curse",date:"05/13/2022",portada:"Lost for Life"},
{title:"American Hardcore",date:"11/29/2021",portada:"They Call Me Renegade"},
{title:"Ladies They Talk About",date:"02/02/2022",portada:"Atlantis: The Lost Empire"},
{title:"Walk in the Sun, A",date:"08/22/2022",portada:"Cobra"},
{title:"The Story of Robin Hood and His Merrie Men",date:"01/07/2022",portada:"Doll, The (Lalka)"},
{title:"Big Doll House, The",date:"07/14/2022",portada:"Cotton Mary"},
{title:"Tis kakomoiras",date:"02/05/2022",portada:"Murders in the Rue Morgue"},
{title:"Divorce of Lady X, The",date:"09/13/2022",portada:"Brotherhood, The"},
{title:"Faust",date:"04/03/2022",portada:"The Hallelujah Handshake"},
{title:"Vincent & Theo",date:"03/26/2022",portada:"The Duke of Burgundy"},
{title:"Would You Rather",date:"12/31/2021",portada:"First Grader, The"},
{title:"Very Brady Sequel, A",date:"12/15/2021",portada:"A Story of Children and Film"},
{title:"Little Mermaid, The",date:"11/22/2021",portada:"Time Without Pity"},
{title:"Young Visiters, The",date:"11/21/2021",portada:"Fullmetal Alchemist the Movie: Conqueror of Shamballa (Gekijô-ban hagane no renkinjutsushi: Shanbara wo yuku mono)"},
{title:"Pokémon the Movie 2000",date:"06/24/2022",portada:"Defiance"},
{title:"Good German, The",date:"10/19/2021",portada:"Hellraiser: Revelations"},
{title:"American Tail, An",date:"02/23/2022",portada:"Shaun of the Dead"},
{title:"Last of the High Kings, The (a.k.a. Summer Fling)",date:"01/13/2022",portada:"King of Fighters, The"},
{title:"Cyborg Girl (Boku no kanojo wa saibôgu)",date:"10/14/2021",portada:"Glory"},
{title:"Asterix and the Vikings (Astérix et les Vikings)",date:"06/14/2022",portada:"Unholy"},
{title:"Miss Congeniality 2: Armed and Fabulous",date:"04/08/2022",portada:"Fragments of an Alms-Film (Fragmentos de um Filme-Esmola: A Sagrada Família)"},
{title:"Pink Saris",date:"03/04/2022",portada:"Parental Guidance"},
{title:"Harry + Max",date:"10/23/2021",portada:"Summer Place, A"},
{title:"Deathtrap",date:"06/30/2022",portada:"Little Lord Fauntleroy"},
{title:"Year of the Comet",date:"12/06/2021",portada:"Tango Kabaree"},
{title:"In a Dark Place",date:"07/31/2022",portada:"Shopping"},
{title:"Dark Touch",date:"08/04/2022",portada:"Futureworld"},
{title:"Boy in Blue, The",date:"10/13/2021",portada:"Fathom"},
{title:"Count Dracula (Nachts, wenn Dracula erwacht)",date:"01/25/2022",portada:"Rollercoaster"},
{title:"Ragtime",date:"12/22/2021",portada:"George Carlin: It's Bad for Ya!"},
{title:"The Thirteen Assassins",date:"10/22/2021",portada:"Hidden Assassin (Shooter, The)"},
{title:"In the Mouth of Madness",date:"02/13/2022",portada:"Heimat - A Chronicle of Germany (Heimat - Eine deutsche Chronik)"},
{title:"Love Hina Again",date:"02/21/2022",portada:"London"},
{title:"Madam Satan",date:"01/08/2022",portada:"Point of No Return"},
{title:"Invasion of Astro-Monster (Godzilla vs. Monster Zero) (Kaijû daisensô)",date:"12/18/2021",portada:"Straightheads (Closure)"},
{title:"Rubber",date:"09/24/2022",portada:"Inserts"},
{title:"Big Animal (Duze zwierze)",date:"07/31/2022",portada:"City, The (Ciudad, La)"},
{title:"Love Punch, The",date:"01/07/2022",portada:"Better Luck Tomorrow"},
{title:"Firm, The",date:"03/09/2022",portada:"Gattaca"},
{title:"Fear Strikes Out",date:"03/04/2022",portada:"Greater Promise, A (Iskateli Schastya)"},
{title:"Cheers for Miss Bishop",date:"09/10/2022",portada:"Year Zero: The Silent Death of Cambodia"},
{title:"Rapid Fire",date:"02/28/2022",portada:"Memory of a Killer, The (Zaak Alzheimer, De)"},
{title:"Tu£sday",date:"02/01/2022",portada:"Power Play"},
{title:"Messenger, The (Ulak)",date:"11/12/2021",portada:"Land"},
{title:"Laggies",date:"07/09/2022",portada:"Bring It On: Fight to the Finish"},
{title:"Stars and Stripes Forever",date:"11/27/2021",portada:"Russell Brand: Messiah Complex"},
{title:"Fast Life",date:"07/21/2022",portada:"Death Racers"},
{title:"Different for Girls",date:"09/14/2022",portada:"Push"},
{title:"Long Walk Home, The",date:"10/31/2021",portada:"Red's Dream"},
{title:"Stereo",date:"10/14/2021",portada:"Basic Instinct 2"},
{title:"Vegas Vacation (National Lampoon's Las Vegas Vacation)",date:"04/05/2022",portada:"All the Fine Young Cannibals"},
{title:"Temptation of St. Tony, The (Püha Tõnu kiusamine)",date:"03/13/2022",portada:"Woman in the Dunes (Suna no onna)"},
{title:"Marooned",date:"01/31/2022",portada:"After the Life"},
{title:"Presto",date:"03/12/2022",portada:"Abominable Dr. Phibes, The"},
{title:"Amber Alert ",date:"01/19/2022",portada:"Starter for 10"},
{title:"Sophie's Choice",date:"10/13/2021",portada:"Kingdom, The"},
{title:"Emmanuel's Gift",date:"02/22/2022",portada:"Philomena"},
{title:"Vali",date:"06/02/2022",portada:"From Above"},
{title:"Nothing in Common",date:"08/17/2022",portada:"Gridlock'd"},
{title:"Satan Met a Lady",date:"07/31/2022",portada:"Dona Flor and Her Two Husbands (Dona Flor e Seus Dois Maridos)"},
{title:"The Fool",date:"08/25/2022",portada:"Joy Division"},
{title:"Cattle Queen of Montana",date:"09/22/2022",portada:"For Love of Ivy"},
{title:"Zus & Zo",date:"05/01/2022",portada:"Outsiders (Ceddo)"},
{title:"We Are the Best! (Vi är bäst!)",date:"05/01/2022",portada:"Flirt"},
{title:"3096 Days",date:"05/27/2022",portada:"Kalevala - Uusi aika"},
{title:"Deadly Circuit (Mortelle randonnée)",date:"02/17/2022",portada:"Ichi"},
{title:"Night Train",date:"03/22/2022",portada:"Adam's Apples (Adams æbler)"},
{title:"Gloria",date:"04/27/2022",portada:"Horror Express"},
{title:"Sleepwalkers",date:"07/29/2022",portada:"Empire"},
{title:"Hatful of Rain, A",date:"07/01/2022",portada:"Milk Money"},
{title:"Jimmy Carter Man from Plains",date:"10/02/2021",portada:"Miami Vice"},
{title:"Amber Alert ",date:"07/09/2022",portada:"Man Apart, A"},
{title:"L.A. Without a Map",date:"07/31/2022",portada:"Too Much Sleep"},
{title:"Funhouse, The",date:"07/04/2022",portada:"Cadillac Man"},
{title:"Win/win",date:"05/31/2022",portada:"Casual Relations"},
{title:"Body and Soul",date:"09/19/2022",portada:"Living Out Loud"},
{title:"Texas Chainsaw Massacre: The Next Generation (a.k.a. The Return of the Texas Chainsaw Massacre)",date:"02/25/2022",portada:"Film ist a Girl & a Gun"},
{title:"TWA Flight 800 ",date:"03/07/2022",portada:"Mujhse Dosti Karoge!"},
{title:"Xtro 2: The Second Encounter",date:"09/06/2022",portada:"Tristana"},
{title:"Out of Balance: ExxonMobil's Impact on Climate Change",date:"05/14/2022",portada:"Late Autumn (Akibiyori)"},
{title:"State of the Union",date:"01/23/2022",portada:"Wonderland"},
{title:"Courage of the Eagles, The (Les aiguilles rouges)",date:"07/10/2022",portada:"Six Pack"},
{title:"Straw Dogs",date:"12/05/2021",portada:"Very Potter Sequel, A"},
{title:"The Man in the Orange Jacket",date:"04/08/2022",portada:"Out-of-Towners, The"},
{title:"Swimming",date:"06/24/2022",portada:"Religulous"},
{title:"Summer of Sam",date:"08/15/2022",portada:"Cloudburst"},
{title:"Männerherzen... und die ganz ganz große Liebe",date:"05/29/2022",portada:"Pudana Last of the Line (Sukunsa viimeinen)"},
{title:"Suburbia",date:"04/23/2022",portada:"Thirteen, The (Trinadtsat)"},
{title:"Polisse",date:"09/20/2022",portada:"One True Thing"},
{title:"Rickshaw Man, The (Muhomatsu no issho)",date:"04/04/2022",portada:"Microphone"},
{title:"No Good Deed",date:"12/09/2021",portada:"Marley & Me"},
{title:"It Happens Every Spring",date:"07/11/2022",portada:"American Friend, The (Amerikanische Freund, Der)"},
{title:"Faster",date:"06/25/2022",portada:"Not Another Not Another Movie"},
{title:"Border Feud",date:"09/14/2022",portada:"Trekkies"},
{title:"Blue Skies",date:"10/30/2021",portada:"They Call Him Bulldozer (Lo chiamavano Bulldozer)"},
{title:"R.I.P.D.",date:"06/11/2022",portada:"Lorna's Silence (Le silence de Lorna)"},
{title:"Hoodwinked!",date:"01/04/2022",portada:"A Gun for Jennifer"},
{title:"Pat and Mike",date:"10/16/2021",portada:"Finian's Rainbow"},
{title:"Maze, The",date:"07/05/2022",portada:"Willard"},
{title:"Rage of Angels: The Story Continues",date:"12/31/2021",portada:"Dark Circles "},
{title:"Lost World: Jurassic Park, The",date:"06/07/2022",portada:"Female Demon Ohyaku (Yôen dokufuden hannya no ohyaku)"},
{title:"In a Better World (Hævnen)",date:"11/22/2021",portada:"Saturday the 14th"},
{title:"Real Cancun, The",date:"06/01/2022",portada:"Failan"},
{title:"Side Out",date:"02/01/2022",portada:"Manhattan Baby"},
{title:"Wing Commander",date:"04/29/2022",portada:"Moon Warriors, The (Zhan shen chuan shuo)"},
{title:"Kagemusha",date:"04/19/2022",portada:"How I Ended This Summer (Kak ya provyol etim letom)"},
{title:"Bookies",date:"04/18/2022",portada:"Jekyll + Hyde"},
{title:"Angels with Dirty Faces",date:"04/25/2022",portada:"Deep Crimson (Profundo carmesí)"},
{title:"Blue Kite, The (Lan feng zheng)",date:"01/17/2022",portada:"The Gallant Hours"},
{title:"Young Bess",date:"10/03/2021",portada:"Someone Like You (Unnaipol Oruvan)"},
{title:"Night Nurse",date:"06/19/2022",portada:"Cry Baby Lane"},
{title:"Pact, The",date:"10/30/2021",portada:"Phil Ochs: There But for Fortune"},
{title:"Love, Honour and Obey",date:"03/09/2022",portada:"Raising Cain"},
{title:"Endless Love",date:"07/24/2022",portada:"Wer"},
{title:"Duck Soup",date:"06/24/2022",portada:"Firecracker"},
{title:"Wild",date:"11/15/2021",portada:"Hairdresser's Husband, The (Le mari de la coiffeuse)"},
{title:"Long Ships, The",date:"10/23/2021",portada:"Bulli: Cooking in Progress, El"},
{title:"Chopping Mall (a.k.a. Killbots)",date:"09/24/2022",portada:"It Might Get Loud"},
{title:"Sweet and Lowdown",date:"10/23/2021",portada:"Evil That Men Do, The"},
{title:"Babymother",date:"08/02/2022",portada:"Dream Land"},
{title:"Missing Person, The",date:"06/15/2022",portada:"Dam Busters, The"},
{title:"Joe Dirt",date:"12/31/2021",portada:"Crash Dive"},
{title:"Wolfen",date:"09/24/2022",portada:"Haunted Echoes"},
{title:"Modify ",date:"04/23/2022",portada:"Absolute Aggression"},
{title:"Mysterious Island, The",date:"12/10/2021",portada:"Lone Wolf and Cub: Baby Cart at the River Styx (Kozure Ôkami: Sanzu no kawa no ubaguruma)"},
{title:"Tormented",date:"09/17/2022",portada:"Adam Resurrected"},
{title:"Chernobyl Diaries",date:"05/05/2022",portada:"Broken Arrow"},
{title:"Fitzwilly",date:"10/09/2021",portada:"See This Movie"},
{title:"Congo",date:"08/16/2022",portada:"Real McCoy, The"},
{title:"Mrs. Doubtfire",date:"09/26/2022",portada:"Skyfall"},
{title:"Sympathy for Delicious",date:"01/03/2022",portada:"Criminal Life of Archibaldo de la Cruz, The (Ensayo de un crimen)"},
{title:"Savage Grace",date:"05/24/2022",portada:"Holding, The"},
{title:"World of Kanako, The (Kawaki.)",date:"08/03/2022",portada:"Meantime"},
{title:"Collision Course",date:"01/22/2022",portada:"Holy Man"},
{title:"American, The",date:"06/02/2022",portada:"Vito"},
{title:"Dream for an Insomniac",date:"12/06/2021",portada:"Soul Man"},
{title:"Growing Pains",date:"10/31/2021",portada:"Clink of Ice, The (a.k.a.: Sound of Ice Cubes, The) (Le bruit des glaçons)"},
{title:"Everybody's Fine (Stanno tutti bene)",date:"08/20/2022",portada:"Daisy Miller"},
{title:"Ordeal, The (Calvaire)",date:"09/07/2022",portada:"Great Mouse Detective, The"},
{title:"3 Simoa",date:"09/02/2022",portada:"Who Pulled the Plug? (Göta kanal eller Vem drog ur proppen?)"},
{title:"Breaking the Waves",date:"02/14/2022",portada:"Beneath Hill 60"},
{title:"Living Out Loud",date:"03/22/2022",portada:"Original Sin"},
{title:"White Fang",date:"01/22/2022",portada:"Life or Something Like It"},
{title:"Diary of a Lost Girl (Tagebuch einer Verlorenen)",date:"09/01/2022",portada:"Legend of the Fist: The Return of Chen Zhen (Jing wu feng yun: Chen Zhen)"},
{title:"Beetle Queen Conquers Tokyo",date:"05/20/2022",portada:"My Joy (Schastye moe)"},
{title:"Watchmen",date:"02/04/2022",portada:"Hard Candy"},
{title:"Freakonomics",date:"10/11/2021",portada:"His New Profession"},
{title:"Gunless",date:"04/25/2022",portada:"Stalag Luft"},
{title:"Bill Maher: Victory Begins at Home",date:"10/11/2021",portada:"President's Analyst, The"},
{title:"48 Hrs.",date:"07/25/2022",portada:"Mean Machine"},
{title:"Batman: The Dark Knight Returns, Part 1",date:"11/13/2021",portada:"Foreign Student"},
{title:"Poltergeist II: The Other Side",date:"11/28/2021",portada:"Just an American Boy"},
{title:"American Tail: Fievel Goes West, An",date:"12/24/2021",portada:"Edmond"},
{title:"Machete",date:"12/11/2021",portada:"Long Day's Journey Into Night"},
{title:"Deadtime Stories",date:"04/05/2022",portada:"Pick-up Artist, The"},
{title:"Blind Horizon",date:"10/15/2021",portada:"Xuxa in Crystal Moon"},
{title:"Far from Heaven",date:"09/25/2022",portada:"Hider in the House"},
{title:"Girl in the Cadillac",date:"12/15/2021",portada:"Maverick"},
{title:"Easy Virtue",date:"09/20/2022",portada:"Charleston"},
{title:"Vice",date:"12/22/2021",portada:"Thirty Seconds Over Tokyo"},
{title:"Frankie and Johnny",date:"11/01/2021",portada:"8MM 2"},
{title:"Valentin (Valentín)",date:"04/22/2022",portada:"Celine and Julie Go Boating (Celine et Julie vont en bateau)"},
{title:"Truth of Lie, The (Die Wahrheit der Lüge)",date:"12/12/2021",portada:"Sweet Karma"},
{title:"Sleep Dealer",date:"12/23/2021",portada:"Young Lieutenant, The (Le petit lieutenant)"},
{title:"Fuhrer Ex (Führer EX)",date:"01/09/2022",portada:"Think Like a Man"},
{title:"Of Human Hearts",date:"04/20/2022",portada:"Man, Woman and the Wall (Kikareta onna no mirareta yoru)"},
{title:"Papillon",date:"07/21/2022",portada:"Mr. North"},
{title:"Children of the Corn",date:"05/04/2022",portada:"Around the Bend"},
{title:"Robe, The",date:"12/01/2021",portada:"Shark Alarm at Müggelsee (Hai Alarm am Müggelsee)"},
{title:"Personal History, Adventures, Experience, & Observation of David Copperfield the Younger, The (a.k.a. David Copperfield)",date:"01/25/2022",portada:"Locals, The"},
{title:"Numbskull Emptybrook in the Army (Uuno Turhapuro armeijan leivissä)",date:"09/10/2022",portada:"Twister"},
{title:"We All Loved Each Other So Much (C'eravamo tanto amati)",date:"03/09/2022",portada:"Alien: Resurrection"},
{title:"Wind Journeys, The (Viajes del viento, Los)",date:"08/23/2022",portada:"Zebrahead"},
{title:"La Morte Rouge",date:"10/17/2021",portada:"Below Sea Level"},
{title:"Tamara",date:"09/23/2022",portada:"Jet Pilot"},
{title:"Unsaid, The",date:"02/07/2022",portada:"Killing Auntie (Zabicie ciotki)"},
{title:"Them (Ils)",date:"11/12/2021",portada:"Manson Family, The"},
{title:"My Brother the Terrorist",date:"02/05/2022",portada:"Inglorious Bastards (Quel maledetto treno blindato)"},
{title:"Crime Zone",date:"01/31/2022",portada:"Supercondriaque"},
{title:"Tiny Toon Adventures: How I Spent My Vacation",date:"08/19/2022",portada:"Proof"},
{title:"Distant Thunder (Ashani Sanket)",date:"03/26/2022",portada:"Whirlygirl"},
{title:"Island in the Sun",date:"09/26/2022",portada:"Truth or Die "},
{title:"Stonehenge Apocalypse",date:"09/15/2022",portada:"Finian's Rainbow"},
{title:"Greatest, The",date:"05/07/2022",portada:"Spies Like Us"},
{title:"SuperBabies: Baby Geniuses 2",date:"05/26/2022",portada:"Shunning, The"},
{title:"Two for the Money",date:"06/08/2022",portada:"Runner, The (Davandeh)"},
{title:"Thief Lord, The",date:"08/23/2022",portada:"Kal Ho Naa Ho"},
{title:"The Violent Professionals",date:"08/28/2022",portada:"Wild One, The"},
{title:"Mr. Thank You (Arigatô-san)",date:"03/25/2022",portada:"Something Wild"},
{title:"Breaking the Silence: Truth and Lies in the War on Terror",date:"11/05/2021",portada:"Petrified Forest, The"},
{title:"North Star (a.k.a. Tashunga)",date:"06/15/2022",portada:"Lille Fridolf and I"},
{title:"Chinese Roulette (Chinesisches Roulette)",date:"06/15/2022",portada:"Crossing Guard, The"},
{title:"Drifting Clouds (Kauas pilvet karkaavat)",date:"03/18/2022",portada:"The Halloween That Almost Wasn't"},
{title:"Strongman",date:"06/19/2022",portada:"Morning Glory"},
{title:"Evil (Ondskan)",date:"08/04/2022",portada:"Monster Walks, The"},
{title:"Capital (Le capital)",date:"06/22/2022",portada:"Killer Klowns from Outer Space"},
{title:"Demons 2 (Dèmoni 2... l'incubo ritorna)",date:"12/01/2021",portada:"Triple Cross"},
{title:"Charlie Chan at the Olympics",date:"03/30/2022",portada:"Dragnet"},
{title:"Hangover Part II, The",date:"07/23/2022",portada:"Officer's Ward (chambre des officiers, La)"},
{title:"The Oscar",date:"03/19/2022",portada:"Fanny"},
{title:"Basketball Diaries, The",date:"08/23/2022",portada:"Legend of Sleepy Hollow, The"},
{title:"Everybody's Woman (La signora di tutti)",date:"05/10/2022",portada:"Evangelion: 1.0 You Are (Not) Alone (Evangerion shin gekijôban: Jo)"},
{title:"Gods Must Be Crazy II, The",date:"03/13/2022",portada:"Chaser, The (Chugyeogja)"},
{title:"Jaws: The Revenge",date:"02/04/2022",portada:"Pinchcliffe Grand Prix (Flåklypa Grand Prix)"},
{title:"True Blue ",date:"06/29/2022",portada:"Sleeping Car, The"},
{title:"Pawnbroker, The",date:"04/14/2022",portada:"Petulia"},
{title:"Home",date:"07/28/2022",portada:"Watermelon Man"},
{title:"Expert, The",date:"02/23/2022",portada:"Poor Little Rich Girl"},
{title:"Yanco ",date:"09/19/2022",portada:"Love Comes Softly"},
{title:"Breakin'",date:"06/24/2022",portada:"Deadly Blessing"},
{title:"Sandpiper, The",date:"05/26/2022",portada:"Challenge, The"},
{title:"Tell Them Who You Are",date:"02/07/2022",portada:"Accomplices (Complices)"},
{title:"Ladrón que roba a ladrón",date:"08/12/2022",portada:"Bungee Jumping of Their Own (Beonjijeompeureul hada)"},
{title:"Failan",date:"12/12/2021",portada:"Nightcrawler"},
{title:"Grand Budapest Hotel, The",date:"12/28/2021",portada:"Lenny Bruce: Swear to Tell the Truth"},
{title:"Trust Us, This Is All Made Up",date:"06/18/2022",portada:"My Man Godfrey"},
{title:"Seven Psychopaths",date:"12/12/2021",portada:"Soul of a Man, The"},
{title:"Caveman",date:"12/13/2021",portada:"Still Crazy"},
{title:"Loves of a Blonde (Lásky jedné plavovlásky)",date:"05/24/2022",portada:"Won't Back Down"},
{title:"Hav Plenty",date:"12/21/2021",portada:"Fear of Flying"},
{title:"Thousand Clouds of Peace, A (Mil nubes de paz cercan el cielo, amor, jamás acabarás de ser amor)",date:"06/28/2022",portada:"Endless Love"},
{title:"Dark Horse, The",date:"07/24/2022",portada:"Chariots of Fire"},
{title:"Sorority House Massacre",date:"09/22/2022",portada:"ReGeneration"},
{title:"Essex Boys",date:"02/24/2022",portada:"Moonlight and Valentino"},
{title:"Birder's Guide to Everything, A",date:"05/08/2022",portada:"Friends of Eddie Coyle, The"},
{title:"In Their Sleep (Dans ton sommeil)",date:"06/16/2022",portada:"Maze, The"},
{title:"War of the Dead - Stone's War ",date:"01/17/2022",portada:"Witches, The (aka Devil's Own, The)"},
{title:"Glasses (Megane)",date:"11/25/2021",portada:"Kahaani"},
{title:"2019: After the Fall of New York",date:"12/08/2021",portada:"Loosies"},
{title:"Praying with Lior",date:"01/22/2022",portada:"Doctor Who"},
{title:"One Night at McCool's",date:"12/25/2021",portada:"19th Wife, The"},
{title:"Stickup, The",date:"04/01/2022",portada:"Dark Habits (Entre tinieblas)"},
{title:"Casino Jack and the United States of Money",date:"06/01/2022",portada:"Mating Habits of the Earthbound Human, The"},
{title:"After Image (Seeing in the Dark)",date:"04/06/2022",portada:"Zero Years, The"},
{title:"Invasion, The",date:"10/20/2021",portada:"Tamara Drewe"},
{title:"Ratcatcher",date:"06/18/2022",portada:"Denise Calls Up"},
{title:"Rear Window",date:"03/16/2022",portada:"Shine of Rainbows, A"},
{title:"Ironweed",date:"05/31/2022",portada:"Home of Our Own, A"},
{title:"Countdown to Zero",date:"08/20/2022",portada:"Kings Row"},
{title:"Happy, Texas",date:"02/18/2022",portada:"Bowery at Midnight"},
{title:"White Dwarf, The (Valkoinen kääpiö)",date:"06/08/2022",portada:"On Earth as It Is in Heaven (Así en el cielo como en la tierra)"},
{title:"Dance of the Dead",date:"05/17/2022",portada:"Polish Wedding"},
{title:"Dust Factory, The",date:"05/03/2022",portada:"Harmful Insect (Gaichu)"},
{title:"Four Nights of a Dreamer (Quatre nuits d'un rêveur)",date:"06/11/2022",portada:"Knockin' on Heaven's Door"},
{title:"Jo Pour Jonathan",date:"04/14/2022",portada:"Waking the Dead"},
{title:"Hitler's Stealth Fighter",date:"03/01/2022",portada:"Evil Toons"},
{title:"Home Alone: The Holiday Heist",date:"12/04/2021",portada:"Letter to Momo, A (Momo e no tegami)"},
{title:"Born Romantic",date:"10/01/2021",portada:"Home Movie"},
{title:"City of Violence, The (Jjakpae)",date:"07/01/2022",portada:"Wild Women"},
{title:"Secret of Roan Inish, The",date:"02/23/2022",portada:"Campfire Tales"},
{title:"It All Starts Today (Ça commence aujourd'hui)",date:"03/21/2022",portada:"Rosewood Lane"},
{title:"Crouching Tiger, Hidden Dragon (Wo hu cang long)",date:"08/05/2022",portada:"Antiviral"},
{title:"Spaced Invaders",date:"05/26/2022",portada:"See You Tomorrow, Everyone"},
{title:"Wrong",date:"03/27/2022",portada:"History of Violence, A"},
{title:"Compulsion",date:"01/18/2022",portada:"Drinking Buddies"},
{title:"Return of Frank Cannon, The",date:"08/31/2022",portada:"Satan's Little Helper"},
{title:"Pete Seeger: The Power of Song",date:"11/26/2021",portada:"World according to Ion B., The (Lumea vazuta de Ion B)"},
{title:"William Shakespeare's Romeo + Juliet",date:"02/09/2022",portada:"Dragon Age: Redemption"},
{title:"Rules of Attraction, The",date:"10/13/2021",portada:"From Within"},
{title:"Girl Who Kicked the Hornet's Nest, The (Luftslottet som sprängdes)",date:"05/12/2022",portada:"Enforcer, The (Gei ba ba de xin)"},
{title:"Faith School Menace?",date:"09/03/2022",portada:"Arcana"},
{title:"Mother and the Whore, The (Maman et la putain, La)",date:"07/22/2022",portada:"Garfield's Fun Fest"},
{title:"Chinoise, La",date:"01/15/2022",portada:"Breaking Away"},
{title:"10 Rillington Place",date:"01/01/2022",portada:"Trouble in Paradise"},
{title:"Night Falls on Manhattan",date:"04/09/2022",portada:"Counterfeit Traitor, The"},
{title:"Rembrandt",date:"03/25/2022",portada:"Sex Up Your Life!"},
{title:"Pretty Poison",date:"02/21/2022",portada:"Clerks"},
{title:"Wolves",date:"08/24/2022",portada:"Demetrius and the Gladiators"},
{title:"Who's the Man?",date:"12/17/2021",portada:"Wake Island"},
{title:"Look Who's Talking",date:"11/23/2021",portada:"Construction, The (En construcción)"},
{title:"Chaperone, The",date:"05/22/2022",portada:"Presenting Lily Mars"},
{title:"Children of Nature (Börn náttúrunnar)",date:"04/23/2022",portada:"Bobby Deerfield"},
{title:"Hovering Over the Water (À Flor do Mar)",date:"10/28/2021",portada:"Undead, The"},
{title:"Intersection",date:"09/25/2022",portada:"Grown Up Movie Star"},
{title:"Wind Chill",date:"02/15/2022",portada:"Ultimate Avengers"},
{title:"Rainmaker, The",date:"07/14/2022",portada:"Balto"},
{title:"I Love You, Alice B. Toklas!",date:"09/04/2022",portada:"Where Were You When the Lights Went Out?"},
{title:"Untouchables, The",date:"04/17/2022",portada:"Mummy: Tomb of the Dragon Emperor, The"},
{title:"Stone Reader",date:"04/17/2022",portada:"Heavy"},
{title:"Cellar, The (Huset vid vägens ände)",date:"03/19/2022",portada:"Midnight Clear, A"},
{title:"Blade II",date:"09/06/2022",portada:"Lost Thing, The"},
{title:"Indictment: The McMartin Trial",date:"03/09/2022",portada:"Antz"},
{title:"Suspended Vocation, The (La vocation suspendue)",date:"12/19/2021",portada:"Resurrecting the Street Walker"},
{title:"My Girl 2",date:"04/26/2022",portada:"Deadline"},
{title:"Lone Ranger and the Lost City of Gold, The",date:"10/05/2021",portada:"Zatoichi the Fugitive (Zatôichi kyôjô-tabi) (Zatôichi 4)"},
{title:"Knack ...and How to Get It, The",date:"05/02/2022",portada:"Maniac Cop 2"},
{title:"Karate Kid, Part III, The",date:"11/25/2021",portada:"Song of Freedom"},
{title:"Twice Born (Venuto al mondo)",date:"01/07/2022",portada:"Excess Baggage"},
{title:"Blue",date:"11/02/2021",portada:"W.C. Fields and Me"},
{title:"Misfortunates, The (De helaasheid der dingen)",date:"12/27/2021",portada:"National Lampoon's Van Wilder"},
{title:"Compliance",date:"09/27/2022",portada:"Happy Time, The"},
{title:"Mega Shark vs. Crocosaurus",date:"08/31/2022",portada:"Pont du Nord, Le"},
{title:"Wild Is the Wind",date:"06/09/2022",portada:"The Inner Circle"},
{title:"Outbreak",date:"09/21/2022",portada:"Delta Force, The"},
{title:"Catfish in Black Bean Sauce",date:"12/08/2021",portada:"Autohystoria"},
{title:"Kimjongilia",date:"05/31/2022",portada:"EDtv"},
{title:"Small Circle of Friends, A",date:"05/30/2022",portada:"American Kickboxer 2 (American Kickboxer 2: To the Death)"},
{title:"Pride of the Yankees, The",date:"05/20/2022",portada:"Merry Widow, The"},
{title:"Interview with a Hitman",date:"08/29/2022",portada:"Watch Out, We're Mad (...Altrimenti ci arrabbiamo!)"},
{title:"Honeymoon Killers, The",date:"11/04/2021",portada:"Stromberg - Der Film"},
{title:"Easy Money",date:"10/06/2021",portada:"Dark Blue"},
{title:"Japan's Longest Day (Nihon no ichiban nagai hi)",date:"05/18/2022",portada:"Cop Land"},
{title:"Company of Wolves, The",date:"04/04/2022",portada:"Watch the Birdie"},
{title:"Exit Humanity",date:"12/29/2021",portada:"Dead or Alive: Final"},
{title:"Me Two (Personne aux deux personnes, La)",date:"12/09/2021",portada:"Ouija"},
{title:"Ali",date:"08/08/2022",portada:"Ivans xtc."},
{title:"Recruit, The",date:"12/31/2021",portada:"Last Legion, The"},
{title:"Four Days of Naples, The (Le quattro giornate di Napoli)",date:"10/25/2021",portada:"Taking Lives"},
{title:"Aces 'N' Eights",date:"06/06/2022",portada:"Dance, Girl, Dance"},
{title:"Buster",date:"09/23/2022",portada:"Timerider: The Adventure of Lyle Swann"},
{title:"From the Sky Down",date:"09/24/2022",portada:"Peter's Friends"},
{title:"Beslan: Three Days in September",date:"07/20/2022",portada:"White Balloon, The (Badkonake sefid)"},
{title:"Light Years Away",date:"04/11/2022",portada:"It's Alive III: Island of the Alive"},
{title:"Aguirre: The Wrath of God (Aguirre, der Zorn Gottes)",date:"06/06/2022",portada:"Double Life, A"},
{title:"Jay And Silent Bob's Super Groovy Cartoon Movie",date:"04/05/2022",portada:"Morning Patrol (Proini peripolos)"},
{title:"Parade",date:"03/09/2022",portada:"Emma"},
{title:"Super Demetrios",date:"10/10/2021",portada:"No More School"},
{title:"I Love You Too",date:"11/03/2021",portada:"Hallam Foe (Mister Foe)"},
{title:"Bullet to the Head",date:"03/10/2022",portada:"Jamaica Inn"},
{title:"Living Wake, The",date:"05/02/2022",portada:"Son of the Mask"},
{title:"Unsaid, The",date:"04/24/2022",portada:"Out of the Blue"},
{title:"Steal Big, Steal Little",date:"10/09/2021",portada:"Giant Claw, The"},
{title:"Weekend at Bernie's II",date:"10/04/2021",portada:"Light Sleeper"},
{title:"Weary River",date:"02/22/2022",portada:"Calloused Hands"},
{title:"Ill Gotten Gains",date:"10/24/2021",portada:"Party Monster"},
{title:"Zeisters (Fat Guy Goes Nutzoid)",date:"05/03/2022",portada:"Trainer on the Beach 2"},
{title:"Blind Menace, The (Shiranui kengyô)",date:"08/25/2022",portada:"Far from the Madding Crowd"},
{title:"6ixtynin9 (Ruang Talok 69)",date:"12/08/2021",portada:"Legion"},
{title:"Island of Lost Souls",date:"03/07/2022",portada:"Ashes and Diamonds (Popiól i diament)"},
{title:"Siege, The",date:"04/27/2022",portada:"Red Chapel, The (Røde kapel, Det)"},
{title:"Dream Land",date:"03/29/2022",portada:"Children On Their Birthdays"},
{title:"Code Conspiracy, The",date:"04/25/2022",portada:"Quigley Down Under"},
{title:"Melvin Goes to Dinner",date:"03/01/2022",portada:"Edge of Darkness"},
{title:"Cosmic Monster, The",date:"02/28/2022",portada:"Acts of Worship "},
{title:"Godzilla, King of the Monsters! (Kaijû-ô Gojira)",date:"06/17/2022",portada:"Hotel Reserve"},
{title:"Shirin",date:"01/17/2022",portada:"Solomon Northup's Odyssey"},
{title:"Plastic Age, The",date:"04/14/2022",portada:"I'm Gonna Git You Sucka"},
{title:"Restaurant",date:"03/08/2022",portada:"Mystery (Fu cheng mi shi)"},
{title:"Clean, Shaven",date:"05/20/2022",portada:"Car Bonus (Autobonus)"},
{title:"Offspring ",date:"06/10/2022",portada:"Home Room"},
{title:"Just a Sigh",date:"12/28/2021",portada:"Kinsey"},
{title:"Iron Island (Jazireh Ahani)",date:"06/22/2022",portada:"David and Lisa"},
{title:"Obama Deception: The Mask Comes Off, The",date:"05/29/2022",portada:"They"},
{title:"Cow, The (Gaav)",date:"12/17/2021",portada:"Stray Dogs (Sag-haye velgard)"},
{title:"Orders to Kill",date:"02/02/2022",portada:"47 Ronin"},
{title:"Pink Cadillac",date:"06/05/2022",portada:"Snow Walker, The"},
{title:"Detention",date:"07/18/2022",portada:"Rio Grande"},
{title:"Secret Things (Choses secrètes)",date:"08/23/2022",portada:"Curse of the Golden Flower (Man cheng jin dai huang jin jia)"},
{title:"Program, The",date:"09/29/2022",portada:"Marley & Me"},
{title:"Martin",date:"06/20/2022",portada:"Spitfire Grill, The"},
{title:"Transformers: Revenge of the Fallen",date:"12/04/2021",portada:"Virus"},
{title:"Staying Alive",date:"12/13/2021",portada:"Skeletons"},
{title:"Once You're Born You Can No Longer Hide (Quando sei nato non puoi più nasconderti)",date:"05/06/2022",portada:"Red Dwarf, The (Nain rouge, Le)"},
{title:"Music of Chance, The",date:"06/30/2022",portada:"Mr Hockey The Gordie Howe Story"},
{title:"Hitch Hike (Autostop rosso sangue) (Naked Prey, The)",date:"08/22/2022",portada:"Carriage to Vienna"},
{title:"Krrish 3",date:"04/24/2022",portada:"Who the Hell Is Juliette? (¿Quién diablos es Juliette?)"},
{title:"Kirikou and the Wild Beast (Kirikou et les bêtes sauvages)",date:"05/03/2022",portada:"Center of the World, The"},
{title:"Ghost Breakers, The",date:"12/24/2021",portada:"Fearless Vampire Killers, The"},
{title:"Foreign Correspondent",date:"12/17/2021",portada:"H6: Diario de un asesino"},
{title:"Machine, The",date:"09/17/2022",portada:"The Amazing Screw-On Head"},
{title:"El Robobo De La Jojoya",date:"12/11/2021",portada:"Captain America II: Death Too Soon"},
{title:"When Animals Dream (Når dyrene drømmer)",date:"08/16/2022",portada:"Donkey Hide (Oslinaya shkura)"},
{title:"Heroic Cops (Jing wang shuang xiong)",date:"09/26/2022",portada:"New Life, A (La vie nouvelle)"},
{title:"Citizen Dog (Mah nakorn)",date:"03/09/2022",portada:"Wolf of Wall Street, The"},
{title:"Get Rich or Die Tryin'",date:"05/28/2022",portada:"Listen Up Philip"},
{title:"Bubble Boy",date:"05/19/2022",portada:"Judgment Night"},
{title:"The Story of Alexander Graham Bell",date:"11/29/2021",portada:"Unexpected Love, An"},
{title:"Somewhere",date:"12/08/2021",portada:"Crooklyn"},
{title:"Taxi 2",date:"01/06/2022",portada:"How I Ended This Summer (Kak ya provyol etim letom)"},
{title:"Silent Partner, The",date:"05/16/2022",portada:"Rock 'N' Roll High School"},
{title:"Uninvited, The",date:"12/15/2021",portada:"Hangin' with the Homeboys"},
{title:"Lower City (Cidade Baixa)",date:"01/10/2022",portada:"Terrorizers, The (Kong bu fen zi)"},
{title:"Run If You Can",date:"12/12/2021",portada:"Cold Around the Heart"},
{title:"What's the Matter with Helen?",date:"04/19/2022",portada:"Monitor, The (Babycall)"},
{title:"Perfect Stranger",date:"11/26/2021",portada:"City by the Sea"},
{title:"Julian Po",date:"08/05/2022",portada:"44500 Max"},
{title:"Won't Anybody Listen?",date:"12/11/2021",portada:"Tamara"},
{title:"Somewhere in the City",date:"05/17/2022",portada:"Crow, The: Wicked Prayer"},
{title:"Harper Valley P.T.A.",date:"10/25/2021",portada:"Faces of Schlock"},
{title:"Phantom Carriage, The (Körkarlen)",date:"03/19/2022",portada:"Angels of the Universe (Englar alheimsins)"},
{title:"Absolute Beginners",date:"03/11/2022",portada:"Caribe"},
{title:"Dane Cook: Vicious Circle",date:"12/25/2021",portada:"Lone Wolf and Cub: Baby Cart in the Land of Demons (Kozure Ôkami: Meifumadô)"},
{title:"Firstborn",date:"02/24/2022",portada:"Secret in Their Eyes, The (El secreto de sus ojos)"},
{title:"Burrowing (Man tänker sitt)",date:"10/25/2021",portada:"Python"},
{title:"Until the End of the World (Bis ans Ende der Welt)",date:"03/02/2022",portada:"Sonatine (Sonachine)"},
{title:"Ursul",date:"02/27/2022",portada:"Sexy Beast"},
{title:"Carmen",date:"07/30/2022",portada:"Last Song, The"},
{title:"Breaking the Maya Code",date:"05/04/2022",portada:"Play the Game"},
{title:"Edge of Madness",date:"08/31/2022",portada:"Alien Escape"},
{title:"Li'l Abner",date:"07/04/2022",portada:"The Harry Hill Movie"},
{title:"Take, The",date:"11/28/2021",portada:"Green Fish (Chorok mulkogi)"},
{title:"The Damned",date:"07/03/2022",portada:"Dragons Forever"},
{title:"Charlotte Gray",date:"09/12/2022",portada:"Collector, The"},
{title:"Rocker, The",date:"03/26/2022",portada:"Ape, The"},
{title:"I'm Gonna Git You Sucka",date:"05/25/2022",portada:"Getaway, The"},
{title:"7 Seconds",date:"07/23/2022",portada:"Truman Show, The"},
{title:"Kid Stays in the Picture, The",date:"04/15/2022",portada:"Twilight Samurai, The (Tasogare Seibei)"},
{title:"Cutter, The",date:"10/09/2021",portada:"We Are Young. We Are Strong."},
{title:"Curse of the Puppet Master (Puppet Master 6: The Curse)",date:"10/24/2021",portada:"Remember Sunday"},
{title:"Bang Bang Club, The",date:"02/12/2022",portada:"Jumbo (Billy Rose's Jumbo)"},
{title:"One Kill",date:"10/12/2021",portada:"Hunting and Gathering (Ensemble, c'est tout)"},
{title:"Born in Flames",date:"02/02/2022",portada:"Love Affair"},
{title:"Off the Menu: The Last Days of Chasen's",date:"05/20/2022",portada:"Nathalie..."},
{title:"Slipstream",date:"07/04/2022",portada:"Stars Fell on Henrietta, The"},
{title:"Suur Tõll",date:"01/14/2022",portada:"Infernal Affairs (Mou gaan dou)"},
{title:"Angels Over Broadway",date:"04/24/2022",portada:"Very British Gangster, A"},
{title:"And Starring Pancho Villa as Himself",date:"04/12/2022",portada:"Another Man's Poison"},
{title:"Inception",date:"05/26/2022",portada:"Far Cry"},
{title:"Love and Bullets",date:"01/18/2022",portada:"Thirst"},
{title:"Wind",date:"01/14/2022",portada:"By the Gun"},
{title:"Jingle All the Way",date:"06/21/2022",portada:"Winnie the Pooh and Tigger Too"},
{title:"From Up on Poppy Hill (Kokuriko-zaka kara)",date:"03/10/2022",portada:"Cleanflix"},
{title:"Of Mice and Men",date:"07/22/2022",portada:"Kismet"},
{title:"El Hada Buena - Una Fábula Peronista",date:"12/23/2021",portada:"Next Karate Kid, The"},
{title:"Stonehenge Apocalypse",date:"04/25/2022",portada:"Promise, The (Versprechen, Das)"},
{title:"Don't Eat the Pictures: Sesame Street at the Metropolitan Museum of Art",date:"08/10/2022",portada:"Clairvoyant, The"},
{title:"Rescue Dawn",date:"05/06/2022",portada:"Wyoming Renegades"},
{title:"Predators",date:"07/04/2022",portada:"Brides of Dracula"},
{title:"Twins",date:"10/14/2021",portada:"LOL (Laughing Out Loud)"},
{title:"Stray Dogs",date:"03/27/2022",portada:"Takedown: The DNA of GSP"},
{title:"Papillon",date:"11/02/2021",portada:"Backflash (Backflash Blues)"},
{title:"Charlie Chan in The Chinese Cat",date:"03/18/2022",portada:"Long Day's Journey Into Night"},
{title:"Bustin' Down the Door",date:"01/26/2022",portada:"Age of Innocence, The"},
{title:"My Friend Henry (Ystäväni Henry)",date:"08/06/2022",portada:"Human Resources Manager, The"},
{title:"Citadel, The",date:"10/24/2021",portada:"Adventures of Priscilla, Queen of the Desert, The"},
{title:"Hollywood and The Pentagon: A Dangerous Liaison",date:"07/10/2022",portada:"The Adventure of Faustus Bidgood"},
{title:"Magic Christmas Tree, The",date:"03/08/2022",portada:"Rocketship X-M"},
{title:"Power 98",date:"10/02/2021",portada:"Incident at Loch Ness"},
{title:"Princess and the Pirate, The",date:"06/17/2022",portada:"Two for the Seesaw"},
{title:"Physical Evidence",date:"10/28/2021",portada:"Frenzy"},
{title:"Guest, The",date:"06/25/2022",portada:"Crude Oasis, The"},
{title:"Double Team",date:"09/20/2022",portada:"My Son the Fanatic"},
{title:"Final Destination",date:"10/05/2021",portada:"Mortified Nation"},
{title:"House of Dracula",date:"04/23/2022",portada:"Lost Boundaries"},
{title:"World Apart, A",date:"11/07/2021",portada:"Man in the Gray Flannel Suit, The"},
{title:"Atomic States of America, The",date:"04/26/2022",portada:"House, The (A Casa)"},
{title:"House of Yes, The",date:"06/16/2022",portada:"Bigger, Stronger, Faster*"},
{title:"Off the Charts: The Song-Poem Story",date:"09/13/2022",portada:"1492: Conquest of Paradise"},
{title:"Bummer (Bumer)",date:"10/24/2021",portada:"Point Break"},
{title:"Play House, The",date:"01/14/2022",portada:"8 Heads in a Duffel Bag"},
{title:"River's Edge",date:"05/03/2022",portada:"Father and Guns (De père en flic)"},
{title:"Zombie Strippers!",date:"02/21/2022",portada:"Milk"},
{title:"Something's Gonna Live",date:"06/11/2022",portada:"Nothing About Robert (Rien sur Robert)"},
{title:"Dog Soldiers",date:"01/04/2022",portada:"Don Is Dead, The"},
{title:"Soupe aux Choux, La",date:"08/02/2022",portada:"Super Bitch"},
{title:"Every Other Weekend (Un week-end sur deux)",date:"12/22/2021",portada:"Boiler Room"},
{title:"Death Proof",date:"02/23/2022",portada:"Möbius"},
{title:"Blue Is the Warmest Color (La vie d'Adèle)",date:"04/13/2022",portada:"Phantom Lady"},
{title:"Brothers Solomon, The",date:"03/24/2022",portada:"Mooz-lum"},
{title:"Tarzan and the Lost City",date:"10/27/2021",portada:"When I Walk"},
{title:"Broken Vessels",date:"07/10/2022",portada:"Perez Family, The"},
{title:"Asterix vs. Caesar (Astérix et la surprise de César)",date:"07/17/2022",portada:"Tracks"},
{title:"8th Wonderland",date:"02/24/2022",portada:"Invisible Woman, The"},
{title:"Stranger on the Prowl (Imbarco a mezzanotte)",date:"10/01/2021",portada:"One Man Against the Organization"},
{title:"Never Let Me Go",date:"06/20/2022",portada:"Take Care of My Cat (Goyangileul butaghae)"},
{title:"Poison",date:"08/27/2022",portada:"True Confession"},
{title:"Murder by Death",date:"07/16/2022",portada:"Bluebeard"},
{title:"Core, The",date:"02/15/2022",portada:"Rat Pfink a Boo Boo"},
{title:"Vesna va veloce",date:"09/10/2022",portada:"Things to Do in Denver When You're Dead"},
{title:"Yanks",date:"05/18/2022",portada:"Edge of Darkness"},
{title:"Slender Thread, The",date:"09/12/2022",portada:"Seventh Seal, The (Sjunde inseglet, Det)"},
{title:"Métamorphose des cloportes, La",date:"10/10/2021",portada:"Lovers & Leavers (Kuutamolla)"},
{title:"Brats, The (Les gamins)",date:"04/03/2022",portada:"Stranger in Town, A"},
{title:"The Man Who Played God",date:"11/14/2021",portada:"Bloody Angels (1732 Høtten: Marerittet har et postnummer)"},
{title:"Ju-on: Black Ghost",date:"02/07/2022",portada:"Vamp"},
{title:"Voyage to the Bottom of the Sea",date:"12/06/2021",portada:"Aliens"},
{title:"Along Came Polly",date:"04/15/2022",portada:"Last Real Men, The (Die letzten Männer)"},
{title:"Children of Heaven, The (Bacheha-Ye Aseman)",date:"06/02/2022",portada:"Pinky"},
{title:"eXistenZ",date:"04/23/2022",portada:"Man-Proof"},
{title:"Crow, The: Wicked Prayer",date:"05/21/2022",portada:"Free Samples"},
{title:"Star Trek: Generations",date:"01/10/2022",portada:"Edge of Heaven, The (Auf der anderen Seite)"},
{title:"Guter Junge",date:"04/29/2022",portada:"Spiders, Part 2: The Diamond Ship, The (Die Spinnen, 2. Teil - Das Brillantenschiff)"},
{title:"Dreams of  a Life",date:"04/05/2022",portada:"Inside"},
{title:"Erased (Expatriate, The)",date:"10/27/2021",portada:"Top of the Food Chain (a.k.a. Invasion!)"},
{title:"Home Page",date:"08/02/2022",portada:"Joan Rivers: A Piece of Work"},
{title:"Nine",date:"05/12/2022",portada:"Among Us (Onder Ons)"},
{title:"Call Her Savage",date:"05/07/2022",portada:"Beautiful Kate"},
{title:"Twenty Bucks",date:"06/09/2022",portada:"Ultraviolet"},
{title:"New Barbarians, The (I nuovi barbari)",date:"08/20/2022",portada:"Case of the Whitechapel Vampire, The"},
{title:"Blindness",date:"11/05/2021",portada:"Drew: The Man Behind the Poster"},
{title:"Vuonna 85",date:"03/20/2022",portada:"Monsieur Lazhar"},
{title:"Anazapta (Black Plague)",date:"02/02/2022",portada:"Message to Love: The Isle of Wight Festival"},
{title:"Truth About Emanuel, The",date:"01/06/2022",portada:"Just 4 Kicks"},
{title:"Happy We (Två killar och en tjej)",date:"03/02/2022",portada:"Troubled Water (DeUsynlige)"},
{title:"Prince of Persia: The Sands of Time",date:"08/16/2022",portada:"Velvet Vampire, The"},
{title:"Athena",date:"05/04/2022",portada:"Manufacturing Dissent"},
{title:"Rock 'n' Roll Nightmare",date:"04/24/2022",portada:"Topper Takes a Trip"},
{title:"Blind Chance (Przypadek)",date:"01/16/2022",portada:"Zebrahead"},
{title:"Blood Beast Terror, The",date:"04/04/2022",portada:"Wild Target"},
{title:"Princess of Mars",date:"03/05/2022",portada:"Texas Chainsaw Massacre, The"},
{title:"Shiri (Swiri)",date:"07/22/2022",portada:"Lon Chaney: A Thousand Faces"},
{title:"DiG!",date:"04/01/2022",portada:"Harvest Month, The (Elokuu)"},
{title:"Most Dangerous Game, The",date:"07/06/2022",portada:"Age of Dinosaurs"},
{title:"Hellhounds on My Trail",date:"09/01/2022",portada:"Under Fire"},
{title:"Fanny",date:"04/06/2022",portada:"Wooden Bridge, The"},
{title:"Lone Wolf and Cub: White Heaven in Hell (Kozure ôkami: Jigoku e ikuzo! Daigorô)",date:"03/08/2022",portada:"Blacksmith Scene"},
{title:"Blue Max, The",date:"04/25/2022",portada:"Paris by Night"},
{title:"Gathering, The",date:"01/07/2022",portada:"Escape Plan"},
{title:"Dilemma, The",date:"08/01/2022",portada:"Return to Snowy River (a.k.a. The Man From Snowy River II)"},
{title:"Zatoichi's Flashing Sword (Zatôichi abare tako) (Zatôichi 7)",date:"12/29/2021",portada:"Miss and the Doctors (Tirez la langue, mademoiselle)"},
{title:"The Things of Life",date:"02/19/2022",portada:"Hanzo the Razor: Sword of Justice (Goyôkiba)"},
{title:"8 Women",date:"07/12/2022",portada:"Deal of the Century"},
{title:"Jewtopia",date:"03/28/2022",portada:"Julian Po"},
{title:"Rosewood",date:"09/19/2022",portada:"Dolls"},
{title:"I Am a Sex Addict",date:"06/06/2022",portada:"Saratov Approach, The"},
{title:"Liability, The",date:"03/13/2022",portada:"Leprechaun: Origins"},
{title:"Children of Glory (Szabadság, szerelem)",date:"02/06/2022",portada:"Crystal Ball, The"},
{title:"Frankenhooker",date:"02/25/2022",portada:"Saw III"},
{title:"Fred & Vinnie",date:"02/10/2022",portada:"Saving God"},
{title:"Along Came Polly",date:"02/24/2022",portada:"Distant Voices, Still Lives"},
{title:"Alice's Restaurant",date:"11/05/2021",portada:"For Greater Glory: The True Story of Cristiada"},
{title:"Acadia Acadia?!? (L'acadie, l'Acadie)",date:"08/04/2022",portada:"Giant of Marathon, The (Battaglia di Maratona, La)"},
{title:"Just Like Heaven",date:"12/01/2021",portada:"Fetishes"},
{title:"Truth About Charlie, The",date:"04/24/2022",portada:"Blame (6 Films to Keep You Awake) (Películas para no dormir: La culpa)"},
{title:"Blame (6 Films to Keep You Awake) (Películas para no dormir: La culpa)",date:"12/25/2021",portada:"Bleak Night"},
{title:"Year of the Wolf, The (Suden vuosi)",date:"09/28/2022",portada:"Devil's Pond"},
{title:"Galaxy Quest",date:"07/22/2022",portada:"Expelled from Paradise"},
{title:"D.O.A.",date:"09/18/2022",portada:"Shape of Things, The"},
{title:"Enemy",date:"08/13/2022",portada:"Night Train to Munich"},
{title:"Dolores Claiborne",date:"01/21/2022",portada:"Don't Come Knocking"},
{title:"Lucky Lady",date:"08/15/2022",portada:"40 Days and 40 Nights"},
{title:"Star for Two, A",date:"04/01/2022",portada:"Kedma"},
{title:"There's Only One Sun",date:"09/04/2022",portada:"Club Sandwich"},
{title:"Body of Lies",date:"02/22/2022",portada:"Alpha Dog"},
{title:"Friends of Eddie Coyle, The",date:"01/30/2022",portada:"Very Bad Things"},
{title:"October Sky",date:"07/22/2022",portada:"Ghost Adventures"},
{title:"Wild Reeds (Les roseaux sauvages)",date:"06/25/2022",portada:"Five Days One Summer"},
{title:"Xtro 2: The Second Encounter",date:"08/24/2022",portada:"Last September, The"},
{title:"Mugger, The (El asaltante)",date:"11/06/2021",portada:"Cross of Lorraine, The"},
{title:"Last of the Mohicans, The",date:"02/15/2022",portada:"Magnificent Ambersons, The"},
{title:"Babe",date:"12/22/2021",portada:"Color Purple, The"},
{title:"Hollow Man II",date:"10/26/2021",portada:"Swiss Family Robinson"},
{title:"Veronica Guerin",date:"08/08/2022",portada:"Dances With the Dragons ( Yu long gong wu)"},
{title:"Atomic Rulers of the World",date:"12/25/2021",portada:"Samurai Spy (Ibun Sarutobi Sasuke)"},
{title:"Pretty in Pink",date:"08/09/2022",portada:"Sucker Punch"},
{title:"Wasteland",date:"01/30/2022",portada:"Barbarian Queen"},
{title:"52 Tuesdays",date:"01/02/2022",portada:"Ruby in Paradise"},
{title:"Stolen (Stolen Lives)",date:"02/06/2022",portada:"Mesmerist, The"},
{title:"No Logo",date:"09/05/2022",portada:"How to Kill Your Neighbor's Dog"},
{title:"St. Francisville Experiment, The",date:"12/30/2021",portada:"Endangered Species"},
{title:"Camel Spiders",date:"10/07/2021",portada:"Mooz-lum"},
{title:"Albert Nobbs",date:"04/27/2022",portada:"The Little Rascals Save the Day"},
{title:"American Pie 2",date:"08/20/2022",portada:"Shirin"},
{title:"Making 'The New World'",date:"12/25/2021",portada:"Cuban Fury"},
{title:"Miss Austen Regrets",date:"05/14/2022",portada:"Girasoli, I (Sunflower)"},
{title:"Ox-Bow Incident, The",date:"05/13/2022",portada:"Nature of Existence, The"},
{title:"Charlie Chan's Chance",date:"06/02/2022",portada:"Whiteout"},
{title:"Cousins in Love (a.k.a. Tender Cousins) (Tendres Cousines)",date:"03/08/2022",portada:"Unexpected Love, An"},
{title:"House IV",date:"05/08/2022",portada:"300 Spartans, The"},
{title:"Last Warrior, The (Last Patrol, The)",date:"08/27/2022",portada:"Bad Girls"},
{title:"Night Gallery",date:"11/18/2021",portada:"The Spiritual Boxer"},
{title:"Someone Like Him (Einer wie Bruno)",date:"02/18/2022",portada:"Daylight Robbery"},
{title:"Gardens of the Night",date:"03/29/2022",portada:"Affair of Love, An (Liaison pornographique, Une)"},
{title:"Kimberly",date:"08/26/2022",portada:"On the Road"},
{title:"JFK: The Smoking Gun",date:"12/08/2021",portada:"Underworld U.S.A."},
{title:"Irene, Go Home! (Irena do domu!)",date:"10/04/2021",portada:"Autism: The Musical"},
{title:"Electronic Labyrinth THX 1138 4EB",date:"07/31/2022",portada:"Charlie Chan's Chance"},
{title:"56 Up",date:"08/11/2022",portada:"Dragonwyck"},
{title:"Arsène Lupin",date:"09/23/2022",portada:"Walk Among the Tombstones, A"},
{title:"Rumble on the Docks",date:"10/14/2021",portada:"Chorus Line, A"},
{title:"Moonraker",date:"11/24/2021",portada:"Home and the World, The (Ghare-Baire)"},
{title:"Alien Cargo",date:"10/08/2021",portada:"Children of Invention"},
{title:"Warning Shadows (Schatten - Eine nächtliche Halluzination)",date:"09/14/2022",portada:"In Their Skin"},
{title:"Atlas Shrugged: Part II",date:"09/20/2022",portada:"Message, The (a.k.a. Mohammad: Messenger of God)"},
{title:"Lovely, Still",date:"02/28/2022",portada:"Cherish"},
{title:"Chipmunk Adventure, The",date:"04/19/2022",portada:"Can Mr. Smith Get to Washington Anymore?"},
{title:"Floating Clouds  (Ukigumo)",date:"06/28/2022",portada:"Painted Fire (Chihwaseon)"},
{title:"Django, Kill... If You Live, Shoot! (Se sei vivo spara)",date:"04/21/2022",portada:"Taking Care of Business"},
{title:"Sometime in August (Mitte Ende August)",date:"04/04/2022",portada:"Monkey's Paw, The"},
{title:"Company You Keep, The",date:"05/29/2022",portada:"All That Jazz"},
{title:"Desperate Hours",date:"03/28/2022",portada:"Triumph of the Will (Triumph des Willens)"},
{title:"Bride of Re-Animator",date:"09/29/2022",portada:"Hungry Hill"},
{title:"Naan Kadavul",date:"02/20/2022",portada:"Lupin III: First Contact (Rupan Sansei: Faasuto Kontakuto)"},
{title:"Jeff, Who Lives at Home",date:"09/14/2022",portada:"Red Riding: 1980"},
{title:"ABCs of Death, The",date:"12/15/2021",portada:"Pale Cocoon (Peiru Kokun)"},
{title:"Undercover Brother",date:"06/29/2022",portada:"Milagro Beanfield War"},
{title:"Complete History of My Sexual Failures, A",date:"10/24/2021",portada:"Hiroshima Mon Amour"},
{title:"Marathon Man",date:"12/16/2021",portada:"Min så kallade pappa"},
{title:"Godzilla vs. SpaceGodzilla (Gojira VS Supesugojira)",date:"01/22/2022",portada:"Lovers on the Bridge, The (Amants du Pont-Neuf, Les)"},
{title:"Cell 211 (Celda 211)",date:"10/18/2021",portada:"Goats"},
{title:"Perestroika",date:"07/03/2022",portada:"Igby Goes Down"},
{title:"See You in the Morning",date:"04/25/2022",portada:"3 Extremes (Three... Extremes) (Saam gaang yi)"},
{title:"River, The",date:"05/17/2022",portada:"Everything or Nothing: The Untold Story of 007"},
{title:"Piggy",date:"11/05/2021",portada:"Closet Land"},
{title:"Beer League",date:"12/28/2021",portada:"Warlords, The (Tau ming chong)"},
{title:"Airplane!",date:"06/24/2022",portada:"Lake City"},
{title:"Wankers, The (Les branleuses)",date:"02/20/2022",portada:"Fuck You, Goethe (Fack Ju Göhte)"},
{title:"Mermaid, The (Rusalka)",date:"07/06/2022",portada:"Boy"},
{title:"Class",date:"10/18/2021",portada:"Family Resemblances (Un air de famille)"},
{title:"Lonely Guy, The",date:"01/31/2022",portada:"Arsène Lupin"},
{title:"Autopsy",date:"08/15/2022",portada:"Birds, the Bees and the Italians, The (Signore & signori)"},
{title:"Donner Pass",date:"01/08/2022",portada:"Julia"},
{title:"In My Country (a.k.a. Country of My Skull)",date:"07/30/2022",portada:"Jim Gaffigan: Obsessed"},
{title:"Miracle Mile",date:"01/18/2022",portada:"In Which We Serve"},
{title:"Secret Adventures of Tom Thumb, The",date:"01/07/2022",portada:"Into the White (Cross of Honour)"},
{title:"Dirty Carnival, A (Biyeolhan geori)",date:"07/10/2022",portada:"Toy, The"},
{title:"She Creature (Mermaid Chronicles Part 1: She Creature)",date:"09/14/2022",portada:"Room Service"},
{title:"Mariachi, El",date:"02/26/2022",portada:"Heavy Metal Parking Lot"},
{title:"Salinger",date:"01/27/2022",portada:"Ecstasy in Entropy"},
{title:"Eva",date:"02/21/2022",portada:"Hi-Line, The"},
{title:"Executioners (Xian dai hao xia zhuan)",date:"05/06/2022",portada:"Of Snails and Men (Despre oameni si melci)"},
{title:"Destination Tokyo",date:"04/08/2022",portada:"Castle of Sand, The (Suna no utsuwa)"},
{title:"Waking Life",date:"06/19/2022",portada:"Billy the Kid"},
{title:"American Graffiti",date:"07/24/2022",portada:"Kronos"},
{title:"Battle of amfAR, The",date:"08/16/2022",portada:"Come Out and Play"},
{title:"Back Stage",date:"10/27/2021",portada:"From Morn to Midnight (Von morgens bis Mitternacht)"},
{title:"Queen of Montreuil",date:"12/11/2021",portada:"Lady in the Lake"},
{title:"Fur: An Imaginary Portrait of Diane Arbus",date:"12/12/2021",portada:"Gangster Squad"},
{title:"Away from Her",date:"10/03/2021",portada:"White Sands"},
{title:"Saving Face",date:"03/15/2022",portada:"Little Big Man"},
{title:"Operation Ganymed",date:"09/24/2022",portada:"Nothing Like the Holidays"},
{title:"The Hatchet Man",date:"12/08/2021",portada:"Vacuuming Completely Nude in Paradise"},
{title:"Nixon by Nixon: In His Own Words",date:"10/07/2021",portada:"Bloodtide"},
{title:"Sonic Outlaws",date:"05/20/2022",portada:"To the Devil a Daughter"},
{title:"Orange County",date:"03/21/2022",portada:"King, The"},
{title:"Muppets, The",date:"07/27/2022",portada:"Rio Bravo"},
{title:"Lodger, The",date:"08/27/2022",portada:"World According to Dick Cheney, The "},
{title:"Slave of Love, A (Raba lyubvi)",date:"08/30/2022",portada:"Captain Horatio Hornblower R.N."},
{title:"Three Smart Girls",date:"04/27/2022",portada:"Prophecy, The"},
{title:"Lady is Willing, The",date:"04/22/2022",portada:"One Hundred Mornings"},
{title:"Goddess of 1967, The",date:"10/13/2021",portada:"The Feminine Touch"},
{title:"Life and Nothing But (Vie et rien d'autre, La)",date:"04/14/2022",portada:"Off Beat"},
{title:"Marina Abramovic: The Artist Is Present",date:"11/23/2021",portada:"Kill by Inches"},
{title:"Brassed Off",date:"06/18/2022",portada:"Beach Boys: An American Family, The"},
{title:"Stepdaughter, The",date:"05/20/2022",portada:"Slipper and the Rose, The"},
{title:"High Noon",date:"06/14/2022",portada:"Monsters vs. Aliens"},
{title:"London After Midnight",date:"07/25/2022",portada:"Sukiyaki Western Django"},
{title:"Step Up 3D",date:"11/08/2021",portada:"Brown Bunny, The"},
{title:"Box of Moon Light",date:"03/20/2022",portada:"Portrait Werner Herzog"},
{title:"Jim Carrey: Unnatural Act",date:"02/28/2022",portada:"Seven Beauties (Pasqualino Settebellezze)"},
{title:"Happiness Never Comes Alone (Un bonheur n'arrive jamais seul)",date:"01/12/2022",portada:"Lightnin'"},
{title:"Man - Woman Wanted (Poszukiwany, poszukiwana)",date:"12/17/2021",portada:"Naked Lunch"},
{title:"True Grit",date:"05/14/2022",portada:"The Uninvited Guest"},
{title:"Hedda Gabler",date:"03/29/2022",portada:"Monster"},
{title:"Diamond Girl",date:"11/20/2021",portada:"96 Minutes "},
{title:"Battlefield Earth",date:"12/15/2021",portada:"Employees Leaving the Lumière Factory"},
{title:"Amateurs, The (Moguls, The)",date:"10/16/2021",portada:"Rhythm of a Crime (Ritam zlocina)"},
{title:"High School",date:"09/12/2022",portada:"Mea Maxima Culpa: Silence in the House of God"},
{title:"Witches, The (Le streghe)",date:"11/05/2021",portada:"Gothika"},
{title:"Devil's Trap, The (Dáblova past)",date:"12/12/2021",portada:"Dumplings (Gaau ji)"},
{title:"Michael Jackson's This Is It",date:"01/08/2022",portada:"Life's a Breeze"},
{title:"Sugar Curtain, The (El telón de azúcar)",date:"11/29/2021",portada:"Shout"},
{title:"Hills Have Eyes Part II, The",date:"08/22/2022",portada:"Rampo (a.k.a. The Mystery of Rampo)"},
{title:"Angry Red Planet, The",date:"06/26/2022",portada:"Season of the Witch"},
{title:"All About Lola (Ce que je sais de Lola) (Lo que sé de Lola)",date:"01/26/2022",portada:"Trader Horn"},
{title:"Lines: Horizontal",date:"08/30/2022",portada:"Dead Men Tell"},
{title:"Silent Partner, The",date:"11/03/2021",portada:"Hawk Is Dying, The"},
{title:"Red Lights",date:"04/16/2022",portada:"C(r)ook (Basta - Rotwein Oder Totsein)"},
{title:"Solitude of Prime Numbers, The",date:"04/23/2022",portada:"December Boys"},
{title:"Mortdecai",date:"04/17/2022",portada:"Watching the Detectives"},
{title:"Food Stamped",date:"08/02/2022",portada:"Winning"},
{title:"West of Memphis",date:"02/16/2022",portada:"Fanatics (Kulman pojat)"},
{title:"Bless the Beasts & Children",date:"04/21/2022",portada:"Clear and Present Danger"},
{title:"Music of Chance, The",date:"08/31/2022",portada:"Mission: Impossible - Ghost Protocol"},
{title:"To Have and Have Not",date:"01/12/2022",portada:"Neo Ned"},
{title:"Key of Life (Kagi-dorobô no mesoddo)",date:"07/12/2022",portada:"Human Resources (Ressources humaines)"},
{title:"Stranger's Heart, A",date:"08/31/2022",portada:"Paradise Lost 3: Purgatory"},
{title:"Running With Scissors",date:"06/10/2022",portada:"Sacro GRA"},
{title:"Thérèse",date:"09/23/2022",portada:"Girls Just Want to Have Fun"},
{title:"First Grader, The",date:"08/27/2022",portada:"Crime and Punishment"},
{title:"Sin of Harold Diddlebock, The",date:"12/14/2021",portada:"Brief Encounter"},
{title:"Odd Thomas",date:"05/30/2022",portada:"Anything Else"},
{title:"Buddy",date:"01/02/2022",portada:"Setup (Set Up)"},
{title:"All the Real Girls",date:"05/21/2022",portada:"Giants and Toys (Kyojin to gangu)"},
{title:"Carnival of Souls",date:"06/21/2022",portada:"Alamo, The"},
{title:"Children of Invention",date:"07/07/2022",portada:"Apostle Peter and The Last Supper"},
{title:"A Girl Walks Home Alone at Night",date:"07/05/2022",portada:"Jeremy"},
{title:"Tar",date:"09/02/2022",portada:"Apocalypto"},
{title:"Old Man and the Sea, The",date:"10/15/2021",portada:"Stranger Within, The"},
{title:"Sweet Sixteen",date:"10/01/2021",portada:"Revolver"},
{title:"Mad Monster Party?",date:"11/11/2021",portada:"Grand Hotel"},
{title:"Executioner, The (Massacre Mafia Style)",date:"11/22/2021",portada:"Thing: Terror Takes Shape, The"},
{title:"Beast of Yucca Flats, The",date:"08/24/2022",portada:"Dead Man's Letters (Pisma myortvogo cheloveka)"},
{title:"Invaders from Space",date:"08/22/2022",portada:"Daylight Robbery"},
{title:"Farewell, Home Sweet Home (Adieu, plancher des vaches!)",date:"09/29/2022",portada:"Park Is Mine, The"},
{title:"Grouse",date:"01/18/2022",portada:"Boondock Saints, The"},
{title:"Fish Child, The (El niño pez)",date:"05/11/2022",portada:"Good Thief, The"},
{title:"Hotel Hell Vacation",date:"04/03/2022",portada:"Rhyme & Reason"},
{title:"Good Guys Wear Black",date:"07/17/2022",portada:"The Cruel Sea"},
{title:"Fear and Trembling (Stupeur et tremblements)",date:"11/25/2021",portada:"German Doctor, The (Wakolda)"},
{title:"Not as a Stranger",date:"05/11/2022",portada:"This Is Not a Film (In film nist)"},
{title:"Madhouse",date:"12/31/2021",portada:"Heavy Petting"},
{title:"Plaisir, Le",date:"05/25/2022",portada:"Station West"},
{title:"When Trumpets Fade",date:"09/12/2022",portada:"Animals are Beautiful People"},
{title:"Rapid Fire",date:"01/14/2022",portada:"The Cheat"},
{title:"Utopia",date:"08/28/2022",portada:"I Will Follow You Into the Dark"},
{title:"My Blue Heaven",date:"10/28/2021",portada:"Hired Hand, The"},
{title:"Zift",date:"05/17/2022",portada:"Our Town"},
{title:"Klown: The Movie (Klovn)",date:"04/02/2022",portada:"Three Musketeers, The"},
{title:"Train Ride to Hollywood",date:"08/11/2022",portada:"The Arrival of Joachim Stiller"},
{title:"Heroes of Telemark, The ",date:"05/30/2022",portada:"Boys from Brazil, The"},
{title:"Bad Men of Missouri",date:"05/24/2022",portada:"Underworld"},
{title:"The Invitation",date:"02/28/2022",portada:"Deadly Tower, The"},
{title:"La guerre des tuques",date:"01/26/2022",portada:"Casino Jack"},
{title:"Spetters",date:"10/16/2021",portada:"American Adobo"},
{title:"White Material",date:"06/12/2022",portada:"Love in the Time of Hysteria (Sólo con tu pareja)"},
{title:"Zombies of Mora Tau",date:"09/18/2022",portada:"Mr Hockey The Gordie Howe Story"},
{title:"My Cousin Rachel",date:"03/11/2022",portada:"Dracula A.D. 1972"},
{title:"Walking Tall",date:"04/21/2022",portada:"Sinbad and the Eye of the Tiger"},
{title:"Good Girl, The",date:"08/02/2022",portada:"Fort McCoy"},
{title:"Les Tuche",date:"12/22/2021",portada:"Aladdin"},
{title:"House of Flying Daggers (Shi mian mai fu)",date:"01/18/2022",portada:"They Call Me Renegade"},
{title:"Gate of Heavenly Peace, The",date:"07/29/2022",portada:"Prodigal Son, The (Tuhlaajapoika)"},
{title:"White Sun of the Desert, The (Beloe solntse pustyni)",date:"07/17/2022",portada:"Snipes"},
{title:"The Lazarus Effect",date:"09/23/2022",portada:"Melissa P."},
{title:"Last Starfighter, The",date:"08/15/2022",portada:"Predictions of Fire (Prerokbe Ognja)"},
{title:"Thank Your Lucky Stars",date:"10/20/2021",portada:"Thirst (Bakjwi)"},
{title:"Lovers & Leavers (Kuutamolla)",date:"10/28/2021",portada:"Tatsumi"},
{title:"Skyscraper (Skyskraber)",date:"11/02/2021",portada:"One-Eyed Jacks"},
{title:"Assembly (Ji jie hao) ",date:"12/26/2021",portada:"Measuring the World (Die Vermessung der Welt)"},
{title:"Cannibal Women in the Avocado Jungle of Death",date:"09/15/2022",portada:"Sailor Who Fell from Grace with the Sea, The"},
{title:"Man, The",date:"12/27/2021",portada:"Ice Princess"}]

